// Extracted tests from src/tui/messages/hook_message.rs
// Auto-generated by extract-tests.sh

use super::*;
use crate::hooks::HookEvent;

    #[test]
    fn hook_message_height_full_expanded_empty_output() {
        let msg = HookMessage {
            event: HookEvent::PreToolUse,
            hook_name: "test.sh".to_string(),
            success: true,
            stdout: String::new(),
            stderr: String::new(),
            tool_name: None,
        };
        let height = msg.height(80, HookDisplay::Full, &Theme::gh_dark());
        assert!(height >= 3); // header + "[no output]"
    }

    #[test]
    fn hook_message_height_minimal() {
        let msg = HookMessage {
            event: HookEvent::Stop,
            hook_name: "save.sh".to_string(),
            success: true,
            stdout: "long output here".to_string(),
            stderr: String::new(),
            tool_name: None,
        };
        let height = msg.height(80, HookDisplay::Minimal, &Theme::gh_dark());
        assert_eq!(height, 1); // single line
    }

    #[test]
    fn hook_message_height_hidden() {
        let msg = HookMessage {
            event: HookEvent::PreToolUse,
            hook_name: "test.sh".to_string(),
            success: true,
            stdout: String::new(),
            stderr: String::new(),
            tool_name: None,
        };
        let height = msg.height(80, HookDisplay::Hidden, &Theme::gh_dark());
        assert_eq!(height, 0);
    }

    #[test]
    fn hook_message_with_tool_name() {
        let msg = HookMessage {
            event: HookEvent::PreToolUse,
            hook_name: "security.sh".to_string(),
            success: true,
            stdout: String::new(),
            stderr: String::new(),
            tool_name: Some("Bash".to_string()),
        };
        // Just check it doesn't panic
        let _height = msg.height(80, HookDisplay::Full, &Theme::gh_dark());
    }
