// Extracted tests from src/tui/messages/system_message.rs
// Auto-generated by extract-tests.sh

use super::*;

    fn make_theme() -> Theme {
        Theme::gh_dark()
    }

    #[test]
    fn height_single_line_short() {
        let msg = SystemMessage { content: "Switched to Design mode.".to_string() };
        assert_eq!(msg.height(80, &make_theme()), 2); // 1 text row + 1 blank
    }

    #[test]
    fn height_single_line_long_wraps() {
        let content = "a".repeat(160);
        let msg = SystemMessage { content };
        assert_eq!(msg.height(80, &make_theme()), 3); // 2 wrapped rows + 1 blank
    }

    #[test]
    fn height_multiline_newlines_counted() {
        // 3 lines, each short → 3 rows + 1 blank = 4
        let msg = SystemMessage { content: "a\nb\nc".to_string() };
        assert_eq!(msg.height(80, &make_theme()), 4);
    }

    #[test]
    fn height_multiline_with_wrapping() {
        // Line 1: 160 chars → 2 rows at width 80
        // Line 2: 10 chars → 1 row
        // Total: 3 rows + 1 blank = 4
        let content = format!("{}\nshort", "a".repeat(160));
        let msg = SystemMessage { content };
        assert_eq!(msg.height(80, &make_theme()), 4);
    }

    #[test]
    fn height_empty_content() {
        let msg = SystemMessage { content: String::new() };
        assert_eq!(msg.height(80, &make_theme()), 2); // max(1) + 1
    }

    #[test]
    fn height_zero_width() {
        let msg = SystemMessage { content: "hello".to_string() };
        assert_eq!(msg.height(0, &make_theme()), 2);
    }

    #[test]
    fn height_old_formula_would_underestimate_multiline() {
        // Old formula: chars().count().div_ceil(width).max(1) + 1
        // "a\nb\nc" = 5 chars, 5/80=0, max(1)=1, +1=2 (WRONG, needs 4)
        let msg = SystemMessage { content: "a\nb\nc".to_string() };
        assert_eq!(msg.height(80, &make_theme()), 4);
    }
