// Extracted tests from src/tui/messages/thinking_message.rs
// Auto-generated by extract-tests.sh

use super::ThinkingMessage;
    use crate::tui::thinking_display::ThinkingDisplay;
    use crate::tui::theme::Theme;

    fn theme() -> Theme {
        Theme::gh_dark()
    }

    #[test]
    fn height_hidden_always_2() {
        let msg = ThinkingMessage {
            reasoning: "some reasoning text\nmore text".to_string(),
        };
        assert_eq!(msg.height_with(80, ThinkingDisplay::Hidden, 5, &theme()), 2);
    }

    #[test]
    fn height_collapsed_always_2() {
        let msg = ThinkingMessage {
            reasoning: "some reasoning text\nmore text".to_string(),
        };
        assert_eq!(msg.height_with(80, ThinkingDisplay::Collapsed, 5, &theme()), 2);
    }

    #[test]
    fn height_expanded_empty_reasoning() {
        let msg = ThinkingMessage {
            reasoning: String::new(),
        };
        assert_eq!(msg.height_with(80, ThinkingDisplay::Expanded, 5, &theme()), 2);
    }

    #[test]
    fn height_expanded_under_limit() {
        let msg = ThinkingMessage {
            reasoning: "line1\nline2\nline3".to_string(),
        };
        // 4 base + 3 visible = 7
        assert_eq!(msg.height_with(80, ThinkingDisplay::Expanded, 5, &theme()), 7);
    }

    #[test]
    fn height_expanded_at_limit() {
        let lines: String = (1..=5).map(|i| format!("line{i}")).collect::<Vec<_>>().join("\n");
        let msg = ThinkingMessage { reasoning: lines };
        // 4 base + 5 visible = 9
        assert_eq!(msg.height_with(80, ThinkingDisplay::Expanded, 5, &theme()), 9);
    }

    #[test]
    fn height_expanded_over_limit() {
        let lines: String = (1..=20).map(|i| format!("line{i}")).collect::<Vec<_>>().join("\n");
        let msg = ThinkingMessage { reasoning: lines };
        // 4 base + 5 visible (capped) = 9
        assert_eq!(msg.height_with(80, ThinkingDisplay::Expanded, 5, &theme()), 9);
    }

    #[test]
    fn height_expanded_custom_max_lines() {
        let lines: String = (1..=10).map(|i| format!("line{i}")).collect::<Vec<_>>().join("\n");
        let msg = ThinkingMessage { reasoning: lines };
        // max_lines=3 → 4 base + 3 visible = 7
        assert_eq!(msg.height_with(80, ThinkingDisplay::Expanded, 3, &theme()), 7);
    }

    #[test]
    fn height_zero_width_returns_2() {
        let msg = ThinkingMessage {
            reasoning: "some text".to_string(),
        };
        assert_eq!(msg.height_with(0, ThinkingDisplay::Expanded, 5, &theme()), 2);
    }
