// Extracted tests from src/tui/activity_indicator.rs
// Auto-generated by extract-tests.sh

use super::*;
use std::time::{Duration, Instant};
use ratatui::style::{Color, Modifier};

    fn make_indicator() -> ActivityIndicator {
        // Set last_tick far enough in the past so tick() doesn't time-gate.
        let mut ind = ActivityIndicator::new();
        ind.last_tick = Instant::now().checked_sub(Duration::from_secs(1)).unwrap();
        ind
    }

    #[test]
    fn tick_bounces_at_start() {
        let mut indicator = make_indicator();
        indicator.sweep_pos = 0;
        indicator.sweep_dir = -1;
        indicator.tick("hello");
        assert_eq!(indicator.sweep_pos, 0);
        assert_eq!(indicator.sweep_dir, 1);
    }

    #[test]
    fn tick_bounces_at_end() {
        let mut indicator = make_indicator();
        indicator.sweep_pos = 4;
        indicator.sweep_dir = 1;
        indicator.tick("hello");
        assert_eq!(indicator.sweep_pos, 4);
        assert_eq!(indicator.sweep_dir, -1);
    }

    #[test]
    fn tick_moves_forward() {
        let mut indicator = make_indicator();
        indicator.tick("hello");
        assert_eq!(indicator.sweep_pos, 1);
    }

    #[test]
    fn tick_moves_backward() {
        let mut indicator = make_indicator();
        indicator.sweep_pos = 3;
        indicator.sweep_dir = -1;
        indicator.tick("hello");
        assert_eq!(indicator.sweep_pos, 2);
    }

    #[test]
    fn tick_single_char_label() {
        let mut indicator = make_indicator();
        indicator.tick("x");
        // max(2) means chars=2, so pos moves to 1 (last index = chars-1 = 1)
        assert_eq!(indicator.sweep_pos, 1);
    }

    #[test]
    fn tick_skips_when_interval_not_reached() {
        let mut indicator = ActivityIndicator::new();
        // last_tick is now, so elapsed < 100ms → no advance
        let old_pos = indicator.sweep_pos;
        indicator.tick("hello");
        assert_eq!(indicator.sweep_pos, old_pos);
    }

    #[test]
    fn render_spans_returns_correct_count() {
        let indicator = ActivityIndicator::new();
        let spans = indicator.render_spans("◐ Streaming ◐", Color::Blue, &Theme::gh_dark());
        assert_eq!(spans.len(), 13);
    }

    #[test]
    fn render_static_returns_correct_count() {
        let indicator = ActivityIndicator::new();
        let spans = indicator.render_static("● Ready ●", Color::Green, &Theme::gh_dark());
        assert_eq!(spans.len(), 9);
    }

    #[test]
    fn render_spans_sweep_pos_is_accent() {
        let mut indicator = ActivityIndicator::new();
        indicator.sweep_pos = 2;
        let spans = indicator.render_spans("hello", Color::Blue, &Theme::gh_dark());
        let theme = Theme::gh_dark();
        // Position 2 should be accent + BOLD
        assert!(spans[2].style.add_modifier.contains(Modifier::BOLD));
        assert_eq!(spans[2].style.fg, Some(theme.accent));
    }
