// Extracted tests from src/tui/app.rs
// Auto-generated by extract-tests.sh

use super::app::App;
use super::chat_state::ChatState;
use super::messages::{ChatMessage, UserMessage, AssistantMessage, SystemMessage};

    // Scroll behavior tests (pinned scroll, auto-scroll)
    #[test]
    fn scroll_up_sets_pinned_scroll_and_disables_auto_scroll() {
        let mut chat = ChatState::new();
        chat.scroll_offset = 10;
        chat.auto_scroll = true;
        chat.pinned_scroll = false;

        chat.scroll_up(5);

        assert_eq!(chat.scroll_offset, 5);
        assert!(!chat.auto_scroll);
        assert!(chat.pinned_scroll);
    }

    #[test]
    fn scroll_down_resumes_auto_scroll_when_at_bottom() {
        let mut chat = ChatState::new();
        chat.scroll_offset = 0;
        chat.last_total_height = 20;
        chat.last_viewport_height = 10;
        chat.pinned_scroll = true;
        chat.auto_scroll = false;

        chat.scroll_down(10);

        assert!(!chat.pinned_scroll);
        assert!(chat.auto_scroll);
    }

    #[test]
    fn scroll_down_does_not_resume_when_not_at_bottom() {
        let mut chat = ChatState::new();
        chat.scroll_offset = 0;
        chat.last_total_height = 100;
        chat.last_viewport_height = 10;
        chat.pinned_scroll = true;
        chat.auto_scroll = false;

        chat.scroll_down(5);

        assert!(chat.pinned_scroll, "pinned should remain when not at bottom");
        assert!(!chat.auto_scroll);
    }

    #[test]
    fn scroll_to_bottom_sets_offset_to_max() {
        let mut chat = ChatState::new();
        chat.scroll_offset = 0;
        chat.last_total_height = 100;
        chat.last_viewport_height = 10;

        chat.scroll_to_bottom();

        assert_eq!(chat.scroll_offset, 90);
    }

    #[test]
    fn is_at_bottom_returns_true_when_no_content() {
        let chat = ChatState::new();
        assert!(chat.is_at_bottom(3), "empty chat should be considered at bottom");
    }

    #[test]
    fn is_at_bottom_returns_true_when_at_exact_bottom() {
        let chat = ChatState {
            scroll_offset: 90,
            last_total_height: 100,
            last_viewport_height: 10,
            ..ChatState::new()
        };
        assert!(chat.is_at_bottom(0), "exact bottom should return true");
    }

    #[test]
    fn is_at_bottom_returns_false_when_scrolled_up() {
        let chat = ChatState {
            scroll_offset: 0,
            last_total_height: 100,
            last_viewport_height: 10,
            ..ChatState::new()
        };
        assert!(!chat.is_at_bottom(3), "scrolled to top should not be at bottom");
    }

    #[test]
    fn auto_scroll_guarded_by_pinned_scroll() {
        // When pinned_scroll is true, auto_scroll should NOT be set
        let pinned_scroll = true;
        let should_set_auto_scroll = !pinned_scroll;
        assert!(!should_set_auto_scroll, "auto_scroll should not be set when pinned");

        let pinned_scroll = false;
        let should_set_auto_scroll = !pinned_scroll;
        assert!(should_set_auto_scroll, "auto_scroll should be set when not pinned");
    }

    // History navigation tests
    #[test]
    fn get_history_message_returns_user_messages_in_reverse_order() {
        let mut app = App::new(
            crate::config::Config::default(),
            std::path::PathBuf::from("."),
        );
        app.chat.chat_messages.push(ChatMessage::User(UserMessage {
            content: "first".to_string(),
        }));
        app.chat.chat_messages.push(ChatMessage::Assistant(AssistantMessage {
            content: "response".to_string(),
        }));
        app.chat.chat_messages.push(ChatMessage::User(UserMessage {
            content: "second".to_string(),
        }));

        assert_eq!(app.get_history_message(0), Some("second"));
        assert_eq!(app.get_history_message(1), Some("first"));
        assert_eq!(app.get_history_message(2), None);
    }

    #[test]
    fn get_history_message_skips_non_user_messages() {
        let mut app = App::new(
            crate::config::Config::default(),
            std::path::PathBuf::from("."),
        );
        app.chat.chat_messages.push(ChatMessage::System(SystemMessage {
            content: "system".to_string(),
        }));
        app.chat.chat_messages.push(ChatMessage::User(UserMessage {
            content: "hello".to_string(),
        }));

        assert_eq!(app.get_history_message(0), Some("hello"));
        assert_eq!(app.get_history_message(1), None);
    }

    #[test]
    fn get_history_message_empty_chat() {
        let app = App::new(
            crate::config::Config::default(),
            std::path::PathBuf::from("."),
        );
        assert_eq!(app.get_history_message(0), None);
    }

    #[test]
    fn history_message_count() {
        let mut app = App::new(
            crate::config::Config::default(),
            std::path::PathBuf::from("."),
        );
        app.chat.chat_messages.push(ChatMessage::User(UserMessage {
            content: "a".to_string(),
        }));
        app.chat.chat_messages.push(ChatMessage::Assistant(AssistantMessage {
            content: "b".to_string(),
        }));
        app.chat.chat_messages.push(ChatMessage::User(UserMessage {
            content: "c".to_string(),
        }));

        assert_eq!(app.history_message_count(), 2);
    }

    #[test]
    fn reset_history_clears_state() {
        let mut app = App::new(
            crate::config::Config::default(),
            std::path::PathBuf::from("."),
        );
        app.editor.history_index = 3;
        app.editor.saved_input = Some("test".to_string());
        app.editor.saved_cursor = 5;

        app.reset_history();

        assert_eq!(app.editor.history_index, 0);
        assert!(app.editor.saved_input.is_none());
        assert_eq!(app.editor.saved_cursor, 0);
    }
