// Extracted tests from src/tui/autocomplete.rs
// Auto-generated by extract-tests.sh

use super::autocomplete::{clamp_scroll, get_query_after_char, handle_skill_autocomplete};
use super::app::App;
use super::mode::AutocompleteMode;
use crossterm::event::{KeyCode, KeyEvent, KeyEventKind, KeyEventState, KeyModifiers};

    #[test]
    fn get_query_after_char_basic() {
        assert_eq!(get_query_after_char("hello @src/main.rs", '@'), "src/main.rs");
    }

    #[test]
    fn get_query_after_char_no_trigger() {
        assert_eq!(get_query_after_char("hello world", '@'), "");
    }

    #[test]
    fn get_query_after_char_trigger_at_end() {
        assert_eq!(get_query_after_char("hello @", '@'), "");
    }

    #[test]
    fn get_query_after_char_multiple_triggers() {
        // Returns text after the LAST trigger
        assert_eq!(get_query_after_char("@a @b @c", '@'), "c");
    }

    #[test]
    fn get_query_after_char_slash() {
        assert_eq!(get_query_after_char("hello /new my model", '/'), "new my model");
    }

    #[test]
    fn get_query_after_char_empty_string() {
        assert_eq!(get_query_after_char("", '@'), "");
    }

    #[test]
    fn get_query_after_char_only_trigger() {
        assert_eq!(get_query_after_char("@", '@'), "");
    }

    // ---------------------------------------------------------------------------
    // clamp_scroll
    // ---------------------------------------------------------------------------

    #[test]
    fn clamp_scroll_selected_in_view() {
        assert_eq!(clamp_scroll(3, 0, 50, 10), 0);
    }

    #[test]
    fn clamp_scroll_selected_below_view() {
        assert_eq!(clamp_scroll(12, 0, 50, 10), 3);
    }

    #[test]
    fn clamp_scroll_selected_above_view() {
        assert_eq!(clamp_scroll(2, 5, 50, 10), 2);
    }

    #[test]
    fn clamp_scroll_at_bottom() {
        // 50 items, page size 10, selected at 49
        assert_eq!(clamp_scroll(49, 40, 50, 10), 40);
    }

    #[test]
    fn clamp_scroll_selected_moves_window_past_end() {
        // 50 items, page size 10, selected at 49, offset at 35
        assert_eq!(clamp_scroll(49, 35, 50, 10), 40);
    }

    #[test]
    fn clamp_scroll_single_item() {
        assert_eq!(clamp_scroll(0, 0, 1, 10), 0);
    }

    #[test]
    fn clamp_scroll_fewer_items_than_page() {
        assert_eq!(clamp_scroll(3, 0, 5, 10), 0);
    }

    #[test]
    fn get_query_after_char_partial_path() {
        // @slide should extract "slide" as query
        assert_eq!(get_query_after_char("@slide", '@'), "slide");
    }

    #[test]
    fn get_query_after_char_full_path() {
        // @slider should extract "slider" as query
        assert_eq!(get_query_after_char("@slider", '@'), "slider");
    }

    #[test]
    fn get_query_after_char_with_path_slash() {
        assert_eq!(get_query_after_char("@src/slide", '@'), "src/slide");
    }

    // ---------------------------------------------------------------------------
    // handle_skill_autocomplete
    // ---------------------------------------------------------------------------

    fn make_key(code: KeyCode, modifiers: KeyModifiers) -> KeyEvent {
        KeyEvent {
            code,
            modifiers,
            kind: KeyEventKind::Press,
            state: KeyEventState::NONE,
        }
    }

    fn make_app() -> App {
        App::new(crate::config::Config::default(), std::path::PathBuf::from("."))
    }

    #[test]
    fn skill_autocomplete_space_dismisses_popup() {
        let mut app = make_app();
        app.editor.input_buffer = "/refine".to_string();
        app.editor.cursor_pos = 7;
        app.editor.autocomplete_mode = AutocompleteMode::Skill {
            matches: vec!["refine".to_string()],
            selected: 0,
            scroll_offset: 0,
        };

        let key = make_key(KeyCode::Char(' '), KeyModifiers::NONE);
        let matches = vec!["refine".to_string()];
        let result = handle_skill_autocomplete(&mut app, &key, &matches, &0, &0);

        assert!(result.unwrap());
        assert_eq!(app.editor.input_buffer, "/refine ");
        assert_eq!(app.editor.cursor_pos, 8);
        assert!(matches!(&app.editor.autocomplete_mode, AutocompleteMode::None));
    }
