// Extracted tests from src/tui/hook_display.rs
// Auto-generated by extract-tests.sh

use super::HookDisplay;

    #[test]
    fn default_is_minimal() {
        assert!(matches!(HookDisplay::default(), HookDisplay::Minimal));
    }

    #[test]
    fn toggle_hidden_to_minimal() {
        assert!(matches!(HookDisplay::Hidden.toggle(), HookDisplay::Minimal));
    }

    #[test]
    fn toggle_minimal_to_full() {
        assert!(matches!(HookDisplay::Minimal.toggle(), HookDisplay::Full));
    }

    #[test]
    fn toggle_full_to_hidden() {
        assert!(matches!(HookDisplay::Full.toggle(), HookDisplay::Hidden));
    }

    #[test]
    fn toggle_full_cycle() {
        let mut mode = HookDisplay::Hidden;
        mode = mode.toggle();
        assert!(matches!(mode, HookDisplay::Minimal));
        mode = mode.toggle();
        assert!(matches!(mode, HookDisplay::Full));
        mode = mode.toggle();
        assert!(matches!(mode, HookDisplay::Hidden));
    }

    #[test]
    fn icon_hidden() {
        assert_eq!(HookDisplay::Hidden.icon(), "●");
    }

    #[test]
    fn icon_minimal() {
        assert_eq!(HookDisplay::Minimal.icon(), "●");
    }

    #[test]
    fn icon_full() {
        assert_eq!(HookDisplay::Full.icon(), "▲");
    }

    #[test]
    fn serde_roundtrip_hidden() {
        let json = serde_json::to_string(&HookDisplay::Hidden).unwrap();
        assert_eq!(json, "\"hidden\"");
        let decoded: HookDisplay = serde_json::from_str(&json).unwrap();
        assert!(matches!(decoded, HookDisplay::Hidden));
    }

    #[test]
    fn serde_roundtrip_minimal() {
        let json = serde_json::to_string(&HookDisplay::Minimal).unwrap();
        assert_eq!(json, "\"minimal\"");
        let decoded: HookDisplay = serde_json::from_str(&json).unwrap();
        assert!(matches!(decoded, HookDisplay::Minimal));
    }

    #[test]
    fn serde_roundtrip_full() {
        let json = serde_json::to_string(&HookDisplay::Full).unwrap();
        assert_eq!(json, "\"full\"");
        let decoded: HookDisplay = serde_json::from_str(&json).unwrap();
        assert!(matches!(decoded, HookDisplay::Full));
    }

    #[test]
    fn palette_mode_display_hidden() {
        let display = HookDisplay::Hidden.palette_mode_display();
        assert_eq!(display, "[hidden → minimal]");
    }

    #[test]
    fn palette_mode_display_minimal() {
        let display = HookDisplay::Minimal.palette_mode_display();
        assert_eq!(display, "[minimal → full]");
    }

    #[test]
    fn palette_mode_display_full() {
        let display = HookDisplay::Full.palette_mode_display();
        assert_eq!(display, "[full → hidden]");
    }
