// Extracted tests from src/tui/status_bar.rs
// Auto-generated by extract-tests.sh

use super::status_bar::{format_k, gradient_color, GRADIENT_GREEN, GRADIENT_YELLOW, GRADIENT_RED};
use super::theme::Theme;
use super::status_bar::interpolate_rgb;
use ratatui::style::Color;

    #[test]
    fn gradient_0_is_green() {
        let color = gradient_color(0.0, &Theme::gh_dark());
        match color {
            Color::Rgb(r, g, b) => {
                assert_eq!(r, GRADIENT_GREEN.0);
                assert_eq!(g, GRADIENT_GREEN.1);
                assert_eq!(b, GRADIENT_GREEN.2);
            }
            _ => panic!("expected Rgb color"),
        }
    }

    #[test]
    fn gradient_0_5_is_yellow() {
        let color = gradient_color(0.5, &Theme::gh_dark());
        match color {
            Color::Rgb(r, g, b) => {
                assert_eq!(r, GRADIENT_YELLOW.0);
                assert_eq!(g, GRADIENT_YELLOW.1);
                assert_eq!(b, GRADIENT_YELLOW.2);
            }
            _ => panic!("expected Rgb color"),
        }
    }

    #[test]
    fn gradient_1_is_red() {
        let color = gradient_color(1.0, &Theme::gh_dark());
        match color {
            Color::Rgb(r, g, b) => {
                assert_eq!(r, GRADIENT_RED.0);
                assert_eq!(g, GRADIENT_RED.1);
                assert_eq!(b, GRADIENT_RED.2);
            }
            _ => panic!("expected Rgb color"),
        }
    }

    #[test]
    fn gradient_clamps_above_1() {
        let color = gradient_color(2.0, &Theme::gh_dark());
        match color {
            Color::Rgb(r, g, b) => {
                assert_eq!(r, GRADIENT_RED.0);
                assert_eq!(g, GRADIENT_RED.1);
                assert_eq!(b, GRADIENT_RED.2);
            }
            _ => panic!("expected Rgb color"),
        }
    }

    #[test]
    fn gradient_clamps_below_0() {
        let color = gradient_color(-0.5, &Theme::gh_dark());
        match color {
            Color::Rgb(r, g, b) => {
                assert_eq!(r, GRADIENT_GREEN.0);
                assert_eq!(g, GRADIENT_GREEN.1);
                assert_eq!(b, GRADIENT_GREEN.2);
            }
            _ => panic!("expected Rgb color"),
        }
    }

    #[test]
    fn gradient_nan_falls_back_to_accent() {
        let color = gradient_color(f64::NAN, &Theme::gh_dark());
        assert_eq!(color, Color::Rgb(0x47, 0x8b, 0xe6));
    }

    #[test]
    fn gradient_midpoint_is_between_green_and_yellow() {
        // 25% should be halfway between green and yellow
        let color = gradient_color(0.25, &Theme::gh_dark());
        let expected = interpolate_rgb(GRADIENT_GREEN, GRADIENT_YELLOW, 0.5);
        assert_eq!(color, expected);
    }

    #[test]
    fn format_k_under_1000() {
        assert_eq!(format_k(500), "500");
    }

    #[test]
    fn format_k_over_1000() {
        assert_eq!(format_k(131072), "131.1k");
    }

    #[test]
    fn format_k_exactly_1000() {
        assert_eq!(format_k(1000), "1.0k");
    }
