// Extracted tests from src/tui/thinking_display.rs
// Auto-generated by extract-tests.sh

use super::ThinkingDisplay;

    #[test]
    fn default_is_collapsed() {
        assert!(matches!(ThinkingDisplay::default(), ThinkingDisplay::Collapsed));
    }

    #[test]
    fn toggle_hidden_to_collapsed() {
        assert!(matches!(ThinkingDisplay::Hidden.toggle(), ThinkingDisplay::Collapsed));
    }

    #[test]
    fn toggle_collapsed_to_expanded() {
        assert!(matches!(ThinkingDisplay::Collapsed.toggle(), ThinkingDisplay::Expanded));
    }

    #[test]
    fn toggle_expanded_to_hidden() {
        assert!(matches!(ThinkingDisplay::Expanded.toggle(), ThinkingDisplay::Hidden));
    }

    #[test]
    fn toggle_full_cycle() {
        let mut mode = ThinkingDisplay::Hidden;
        mode = mode.toggle();
        assert!(matches!(mode, ThinkingDisplay::Collapsed));
        mode = mode.toggle();
        assert!(matches!(mode, ThinkingDisplay::Expanded));
        mode = mode.toggle();
        assert!(matches!(mode, ThinkingDisplay::Hidden));
    }

    #[test]
    fn icon_hidden_is_empty() {
        assert_eq!(ThinkingDisplay::Hidden.icon(), "");
    }

    #[test]
    fn icon_collapsed_is_triangle_down() {
        assert_eq!(ThinkingDisplay::Collapsed.icon(), "▼");
    }

    #[test]
    fn icon_expanded_is_triangle_up() {
        assert_eq!(ThinkingDisplay::Expanded.icon(), "▲");
    }

    #[test]
    fn serde_roundtrip_hidden() {
        let json = serde_json::to_string(&ThinkingDisplay::Hidden).unwrap();
        assert_eq!(json, "\"hidden\"");
        let decoded: ThinkingDisplay = serde_json::from_str(&json).unwrap();
        assert!(matches!(decoded, ThinkingDisplay::Hidden));
    }

    #[test]
    fn serde_roundtrip_collapsed() {
        let json = serde_json::to_string(&ThinkingDisplay::Collapsed).unwrap();
        assert_eq!(json, "\"collapsed\"");
        let decoded: ThinkingDisplay = serde_json::from_str(&json).unwrap();
        assert!(matches!(decoded, ThinkingDisplay::Collapsed));
    }

    #[test]
    fn serde_roundtrip_expanded() {
        let json = serde_json::to_string(&ThinkingDisplay::Expanded).unwrap();
        assert_eq!(json, "\"expanded\"");
        let decoded: ThinkingDisplay = serde_json::from_str(&json).unwrap();
        assert!(matches!(decoded, ThinkingDisplay::Expanded));
    }

    #[test]
    fn palette_mode_display_hidden() {
        let display = ThinkingDisplay::Hidden.palette_mode_display();
        assert_eq!(display, "[hidden → collapsed]");
    }

    #[test]
    fn palette_mode_display_collapsed() {
        let display = ThinkingDisplay::Collapsed.palette_mode_display();
        assert_eq!(display, "[collapsed → expanded]");
    }

    #[test]
    fn palette_mode_display_expanded() {
        let display = ThinkingDisplay::Expanded.palette_mode_display();
        assert_eq!(display, "[expanded → hidden]");
    }
