// Extracted tests from src/tui/editor/commands.rs
// Auto-generated by extract-tests.sh

use super::{fuzzy_match_case_insensitive, get_palette_commands, fuzzy_match_palette_commands, parse_file_references};

    // ---------------------------------------------------------------------------
    // fuzzy_match_case_insensitive
    // ---------------------------------------------------------------------------

    #[test]
    fn fuzzy_exact_match() {
        assert!(fuzzy_match_case_insensitive("new", "new").is_some());
    }

    #[test]
    fn fuzzy_case_insensitive() {
        assert!(fuzzy_match_case_insensitive("NEW", "new").is_some());
        assert!(fuzzy_match_case_insensitive("New", "new").is_some());
    }

    #[test]
    fn fuzzy_partial_match() {
        assert!(fuzzy_match_case_insensitive("nw", "new").is_some());
    }

    #[test]
    fn fuzzy_no_match() {
        assert!(fuzzy_match_case_insensitive("xyz", "new").is_none());
    }

    #[test]
    fn fuzzy_consecutive_bonus() {
        let partial = fuzzy_match_case_insensitive("nw", "new").unwrap();
        let consecutive = fuzzy_match_case_insensitive("ne", "new").unwrap();
        assert!(consecutive > partial);
    }

    #[test]
    fn fuzzy_slider_in_path() {
        let result = fuzzy_match_case_insensitive("slider", "src/components/slider.rs");
        assert!(result.is_some());
    }

    #[test]
    fn fuzzy_slide_in_path() {
        let result = fuzzy_match_case_insensitive("slide", "src/components/slider.rs");
        assert!(result.is_some());
    }

    #[test]
    fn fuzzy_sli_in_path() {
        let result = fuzzy_match_case_insensitive("sli", "src/components/slider.rs");
        assert!(result.is_some());
    }

    #[test]
    fn fuzzy_sl_in_path() {
        let result = fuzzy_match_case_insensitive("sl", "src/components/slider.rs");
        assert!(result.is_some());
    }

    #[test]
    fn fuzzy_empty_needle() {
        assert!(fuzzy_match_case_insensitive("", "anything").is_some());
    }

    #[test]
    fn fuzzy_empty_haystack() {
        assert!(fuzzy_match_case_insensitive("x", "").is_none());
    }

    // ---------------------------------------------------------------------------
    // parse_file_references
    // ---------------------------------------------------------------------------

    #[test]
    fn parse_file_refs_single() {
        let refs = parse_file_references("hello @src/main.rs world");
        assert_eq!(refs, vec!["src/main.rs"]);
    }

    #[test]
    fn parse_file_refs_multiple() {
        let refs = parse_file_references("@a/b @c/d.txt");
        assert_eq!(refs.len(), 2);
        assert!(refs.contains(&"a/b".to_string()));
        assert!(refs.contains(&"c/d.txt".to_string()));
    }

    #[test]
    fn parse_file_refs_ignores_slash_commands() {
        let refs = parse_file_references("/new @src/main.rs");
        assert_eq!(refs, vec!["src/main.rs"]);
    }

    #[test]
    fn parse_file_refs_empty() {
        let refs = parse_file_references("hello world");
        assert!(refs.is_empty());
    }

    #[test]
    fn parse_file_refs_max_8() {
        let input = "@a/b @c/d @e/f @g/h @i/j @k/l @m/n @o/p @q/r";
        let refs = parse_file_references(input);
        assert!(refs.len() <= 8);
    }

    #[test]
    fn parse_file_refs_accepts_simple_names() {
        let refs = parse_file_references("@hello");
        assert_eq!(refs, vec!["hello"]);
    }

    // ---------------------------------------------------------------------------
    // Palette commands
    // ---------------------------------------------------------------------------

    #[test]
    fn palette_commands_has_expected_count() {
        let commands = get_palette_commands();
        assert_eq!(commands.len(), 12);
    }

    #[test]
    fn palette_commands_has_quit() {
        let commands = get_palette_commands();
        let quit = commands.iter().find(|c| c.id == "quit");
        assert!(quit.is_some());
        assert_eq!(quit.unwrap().name, "quit");
    }

    #[test]
    fn palette_commands_has_toggle_hook_mode() {
        let commands = get_palette_commands();
        let toggle = commands.iter().find(|c| c.id == "toggle_hook_mode");
        assert!(toggle.is_some());
        assert_eq!(toggle.unwrap().name, "toggle hook display");
    }

    #[test]
    fn palette_fuzzy_match_q_finds_quit() {
        let results = fuzzy_match_palette_commands("q", 10);
        assert!(!results.is_empty(), "'q' should match 'quit'");
        assert!(
            results.iter().any(|(_, c)| c.id == "quit"),
            "Results should contain 'quit' command"
        );
    }

    #[test]
    fn palette_fuzzy_match_empty_returns_all() {
        let results = fuzzy_match_palette_commands("", 20);
        assert_eq!(results.len(), 12);
    }

    #[test]
    fn palette_fuzzy_match_new_finds_new() {
        let results = fuzzy_match_palette_commands("new", 10);
        assert!(!results.is_empty());
        assert_eq!(results[0].1.id, "new");
    }

    #[test]
    fn palette_fuzzy_match_toggle_finds_all_toggles() {
        let results = fuzzy_match_palette_commands("toggle", 10);
        assert!(results.len() >= 3);
        assert!(results.iter().any(|(_, c)| c.id == "toggle_thinking"));
        assert!(results.iter().any(|(_, c)| c.id == "toggle_tool_output"));
        assert!(results.iter().any(|(_, c)| c.id == "toggle_hook_mode"));
    }

    #[test]
    fn palette_fuzzy_match_hook_finds_hook_toggle() {
        let results = fuzzy_match_palette_commands("hook", 10);
        assert!(!results.is_empty());
        assert!(results.iter().any(|(_, c)| c.id == "toggle_hook_mode"));
    }

    #[test]
    fn palette_fuzzy_match_no_match_returns_empty() {
        let results = fuzzy_match_palette_commands("xyznonexistent", 10);
        assert!(results.is_empty());
    }
