// Extracted tests from src/tui/editor/cursor.rs
// Auto-generated by extract-tests.sh

use super::{cursor_line_col, cursor_left, cursor_right, cursor_up, cursor_down, cursor_home, cursor_end, cursor_backspace, cursor_delete, display_width_to_byte_offset, cursor_up_visual, cursor_down_visual};

    // ---------------------------------------------------------------------------
    // cursor_line_col
    // ---------------------------------------------------------------------------

    #[test]
    fn cursor_line_col_empty_string() {
        assert_eq!(cursor_line_col("", 0), (0, 0));
    }

    #[test]
    fn cursor_line_col_single_line() {
        assert_eq!(cursor_line_col("hello", 0), (0, 0));
        assert_eq!(cursor_line_col("hello", 2), (0, 2));
        assert_eq!(cursor_line_col("hello", 5), (0, 5));
        assert_eq!(cursor_line_col("hello", 100), (0, 5)); // clamped
    }

    #[test]
    fn cursor_line_col_multiline() {
        let input = "abc\ndef\nghi";
        assert_eq!(cursor_line_col(input, 0), (0, 0));   // 'a'
        assert_eq!(cursor_line_col(input, 2), (0, 2));   // 'c'
        assert_eq!(cursor_line_col(input, 3), (0, 3));   // on '\n' → end of line 0
        assert_eq!(cursor_line_col(input, 4), (1, 0));   // 'd'
        assert_eq!(cursor_line_col(input, 6), (1, 2));   // 'f'
        assert_eq!(cursor_line_col(input, 8), (2, 0));   // 'g'
        assert_eq!(cursor_line_col(input, 11), (2, 3));  // end
    }

    #[test]
    fn cursor_line_col_on_newline() {
        let input = "a\nb";
        assert_eq!(cursor_line_col(input, 1), (0, 1)); // on '\n' → (0, 1) = end of line 0
    }

    // ---------------------------------------------------------------------------
    // cursor_left
    // ---------------------------------------------------------------------------

    #[test]
    fn cursor_left_normal() {
        assert_eq!(cursor_left("hello", 5), 4);
        assert_eq!(cursor_left("hello", 3), 2);
    }

    #[test]
    fn cursor_left_at_start() {
        assert_eq!(cursor_left("hello", 0), 0);
        assert_eq!(cursor_left("", 0), 0);
    }

    #[test]
    fn cursor_left_at_line_start_joins_to_prev() {
        let input = "abc\ndef";
        // pos=4 is 'd' (start of line 1). Before is '\n', so move to end of line 0.
        assert_eq!(cursor_left(input, 4), 3); // '3' is the '\n' position
    }

    #[test]
    fn cursor_left_on_first_line() {
        let input = "abc\ndef";
        assert_eq!(cursor_left(input, 2), 1);
    }

    // ---------------------------------------------------------------------------
    // cursor_right
    // ---------------------------------------------------------------------------

    #[test]
    fn cursor_right_normal() {
        assert_eq!(cursor_right("hello", 0), 1);
        assert_eq!(cursor_right("hello", 3), 4);
    }

    #[test]
    fn cursor_right_at_end() {
        assert_eq!(cursor_right("hello", 5), 5);
        assert_eq!(cursor_right("", 0), 0);
    }

    #[test]
    fn cursor_right_on_newline_skips_to_next_line() {
        let input = "a\nb";
        assert_eq!(cursor_right(input, 1), 2); // '\n' → 'b'
    }

    #[test]
    fn cursor_right_at_end_of_last_line() {
        let input = "a\nb";
        assert_eq!(cursor_right(input, 3), 3);
    }

    // ---------------------------------------------------------------------------
    // cursor_up
    // ---------------------------------------------------------------------------

    #[test]
    fn cursor_up_normal() {
        let input = "abc\ndef\nghi";
        // pos=8 is 'g' (line 2, col 0). Up → line 1, col 0 = 'd' = pos 4
        assert_eq!(cursor_up(input, 8), 4);
    }

    #[test]
    fn cursor_up_on_first_line_noop() {
        let input = "abc\ndef";
        assert_eq!(cursor_up(input, 0), 0);
        assert_eq!(cursor_up(input, 2), 2);
    }

    #[test]
    fn cursor_up_clamps_column() {
        let input = "a\nabcdef";
        // pos=6 is 'f' (line 1, col 5). Up → line 0 has len 1, clamp col to 1 = pos 1
        assert_eq!(cursor_up(input, 6), 1);
    }

    #[test]
    fn cursor_up_from_middle() {
        let input = "hello\nworld";
        // pos=8 is 'r' (line 1, col 2). Up → line 0, col 2 = pos 2
        assert_eq!(cursor_up(input, 8), 2);
    }

    // ---------------------------------------------------------------------------
    // cursor_down
    // ---------------------------------------------------------------------------

    #[test]
    fn cursor_down_normal() {
        let input = "abc\ndef\nghi";
        // pos=0 is 'a' (line 0, col 0). Down → line 1, col 0 = 'd' = pos 4
        assert_eq!(cursor_down(input, 0), 4);
    }

    #[test]
    fn cursor_down_on_last_line_noop() {
        let input = "abc\ndef";
        assert_eq!(cursor_down(input, 4), 4);
        assert_eq!(cursor_down(input, 6), 6);
    }

    #[test]
    fn cursor_down_clamps_column() {
        let input = "abcdef\na";
        // pos=3 is 'd' (line 0, col 3). Down → line 1 has len 1, clamp col to 1 = pos 8 (end of line)
        assert_eq!(cursor_down(input, 3), 8);
    }

    #[test]
    fn cursor_down_from_middle() {
        let input = "hello\nworld";
        // pos=2 is 'l' (line 0, col 2). Down → line 1, col 2 = pos 8
        assert_eq!(cursor_down(input, 2), 8);
    }

    // ---------------------------------------------------------------------------
    // cursor_home
    // ---------------------------------------------------------------------------

    #[test]
    fn cursor_home_first_line() {
        assert_eq!(cursor_home("hello", 3), 0);
    }

    #[test]
    fn cursor_home_middle_line() {
        let input = "abc\ndef";
        assert_eq!(cursor_home(input, 6), 4); // 'f' → 'd'
    }

    #[test]
    fn cursor_home_last_line() {
        let input = "a\nb\nc";
        assert_eq!(cursor_home(input, 4), 4); // 'c' → 'c' (already at home)
    }

    // ---------------------------------------------------------------------------
    // cursor_end
    // ---------------------------------------------------------------------------

    #[test]
    fn cursor_end_first_line_not_last() {
        let input = "abc\ndef";
        assert_eq!(cursor_end(input, 0), 3); // 'a' → end of "abc" (pos 3 = '\n')
    }

    #[test]
    fn cursor_end_last_line() {
        let input = "abc\ndef";
        assert_eq!(cursor_end(input, 4), 7); // 'd' → end (pos 7 = input.len())
    }

    #[test]
    fn cursor_end_middle_line() {
        let input = "ab\ncde\nf";
        assert_eq!(cursor_end(input, 5), 6); // 'e' → end of "cde" (pos 6 = '\n')
    }

    // ---------------------------------------------------------------------------
    // cursor_backspace
    // ---------------------------------------------------------------------------

    #[test]
    fn cursor_backspace_normal() {
        let mut input = String::from("hello");
        let mut pos = 5;
        cursor_backspace(&mut input, &mut pos);
        assert_eq!(input, "hell");
        assert_eq!(pos, 4);
    }

    #[test]
    fn cursor_backspace_at_start() {
        let mut input = String::from("hello");
        let mut pos = 0;
        cursor_backspace(&mut input, &mut pos);
        assert_eq!(input, "hello");
        assert_eq!(pos, 0);
    }

    #[test]
    fn cursor_backspace_on_newline_joins_lines() {
        let mut input = String::from("ab\ncd");
        let mut pos = 3; // 'c'
        cursor_backspace(&mut input, &mut pos);
        assert_eq!(input, "abcd");
        assert_eq!(pos, 2);
    }

    #[test]
    fn cursor_backspace_empty_string() {
        let mut input = String::new();
        let mut pos = 0;
        cursor_backspace(&mut input, &mut pos);
        assert!(input.is_empty());
        assert_eq!(pos, 0);
    }

    // ---------------------------------------------------------------------------
    // cursor_delete
    // ---------------------------------------------------------------------------

    #[test]
    fn cursor_delete_normal() {
        let mut input = String::from("hello");
        let mut pos = 1; // 'e'
        cursor_delete(&mut input, &mut pos);
        assert_eq!(input, "hllo"); // 'e' deleted
        assert_eq!(pos, 1);
    }

    #[test]
    fn cursor_delete_at_end() {
        let mut input = String::from("hello");
        let mut pos = 5;
        cursor_delete(&mut input, &mut pos);
        assert_eq!(input, "hello");
    }

    #[test]
    fn cursor_delete_on_newline_joins_lines() {
        let mut input = String::from("ab\ncd");
        let mut pos = 2; // on '\n'
        cursor_delete(&mut input, &mut pos);
        assert_eq!(input, "abcd");
        assert_eq!(pos, 2); // cursor stays
    }

    #[test]
    fn cursor_delete_empty_string() {
        let mut input = String::new();
        let mut pos = 0;
        cursor_delete(&mut input, &mut pos);
        assert!(input.is_empty());
    }

    // ---------------------------------------------------------------------------
    // UTF-8 multi-byte character tests
    // ---------------------------------------------------------------------------

    #[test]
    fn cursor_left_multibyte_german_umlaut() {
        // ö = U+00F6, UTF-8: 0xC3 0xB6 (2 bytes)
        let input = "ö";
        assert_eq!(cursor_left(input, 2), 0); // left from end → start
        assert_eq!(cursor_left(input, 0), 0); // left at start → no-op
        assert_eq!(cursor_left(input, 1), 0); // left from mid-char → start (char boundary)
    }

    #[test]
    fn cursor_right_multibyte_german_umlaut() {
        let input = "ö";
        assert_eq!(cursor_right(input, 0), 2); // right from start → end (skips full char)
        assert_eq!(cursor_right(input, 2), 2); // right at end → no-op
    }

    #[test]
    fn cursor_left_right_multibye_mixed() {
        // "höl" = h(1) + ö(2) + l(1) = 4 bytes
        let input = "höl";
        assert_eq!(cursor_right(input, 0), 1); // h → ö
        assert_eq!(cursor_right(input, 1), 3); // ö → l
        assert_eq!(cursor_right(input, 3), 4); // l → end
        assert_eq!(cursor_left(input, 4), 3); // end → l
        assert_eq!(cursor_left(input, 3), 1); // l → ö
        assert_eq!(cursor_left(input, 1), 0); // ö → h
    }

    #[test]
    fn cursor_backspace_multibyte() {
        // "hölle" = h(1) ö(2) l(1) l(1) e(1) = 6 bytes
        // pos = 6 means cursor PAST end (after 'e')
        let mut input = String::from("hölle");
        let mut pos = 6;
        cursor_backspace(&mut input, &mut pos);
        assert_eq!(input, "höll"); // 'e' removed
        assert_eq!(pos, 5);

        // Backspace through 'ö' (2-byte char)
        // "hö" = h(1) ö(2) = 3 bytes, pos = 3 means cursor PAST end
        let mut input = String::from("hö");
        let mut pos = 3;
        cursor_backspace(&mut input, &mut pos);
        assert_eq!(input, "h"); // 'ö' removed
        assert_eq!(pos, 1);
    }

    #[test]
    fn cursor_delete_multibyte() {
        let mut input = String::from("öh");
        let mut pos = 0;
        cursor_delete(&mut input, &mut pos);
        assert_eq!(input, "h");
        assert_eq!(pos, 0);
    }

    #[test]
    fn cursor_line_col_multibyte() {
        let input = "öäü"; // 6 bytes: ö(2) ä(2) ü(2)
        assert_eq!(cursor_line_col(input, 0), (0, 0));
        assert_eq!(cursor_line_col(input, 2), (0, 2)); // after ö
        assert_eq!(cursor_line_col(input, 4), (0, 4)); // after ä
        assert_eq!(cursor_line_col(input, 6), (0, 6)); // end
    }

    #[test]
    fn cursor_left_multibyte_newline() {
        // "a\nö" = a(1) \n(1) ö(2) = 4 bytes
        let input = "a\nö";
        // pos=3 is start of 'ö' on line 1
        // prev char is '\n', so cursor_left lands on '\n' (pos=1)
        assert_eq!(cursor_left(input, 3), 1);
        // pos=1 is '\n' on line 0, col=1
        // prev char is 'a', so cursor_left → pos=0
        assert_eq!(cursor_left(input, 1), 0);
    }

    #[test]
    fn cursor_up_down_multibyte() {
        // "ö\nä" = ö(2) \n(1) ä(2) = 5 bytes
        let input = "ö\nä";
        // pos=3 is 'ä' (line 1, col 0)
        assert_eq!(cursor_up(input, 3), 0); // → 'ö' (line 0, col 0)
        assert_eq!(cursor_down(input, 0), 3); // → 'ä' (line 1, col 0)
    }

    #[test]
    fn cursor_home_end_multibyte() {
        let input = "öäü"; // 6 bytes
        assert_eq!(cursor_home(input, 5), 0);
        assert_eq!(cursor_end(input, 0), 6);
    }

    #[test]
    fn cursor_multibyte_emoji() {
        // 😀 = U+1F600, UTF-8: 4 bytes (F0 9F 98 80)
        let input = "😀a";
        assert_eq!(cursor_right(input, 0), 4); // skip full emoji
        assert_eq!(cursor_left(input, 5), 4); // back to emoji
        assert_eq!(cursor_left(input, 4), 0); // back to start

        let mut input = String::from("a😀");
        let mut pos = 5;
        cursor_backspace(&mut input, &mut pos);
        assert_eq!(input, "a");
        assert_eq!(pos, 1);

        let mut input = String::from("😀");
        let mut pos = 0;
        cursor_delete(&mut input, &mut pos);
        assert_eq!(input, "");
        assert_eq!(pos, 0);
    }

    // ---------------------------------------------------------------------------
    // Regression: cursor_up/down must not land inside multi-byte characters
    // ---------------------------------------------------------------------------

    #[test]
    fn cursor_down_ascii_to_multibyte_rounds_down() {
        // "abcde\na─" — line 0 is 5 bytes (ASCII), line 1 is 4 bytes (a(1) + ─(3))
        // Cursor at byte 3 in line 0 ('d'). Down should NOT land at byte 3 in line 1
        // (which is inside ─ at bytes 1..4). Should round down to byte 1 (after 'a').
        let input = "abcde\na─";
        let result = cursor_down(input, 3);
        // Byte 3 in line 1 is inside '─'. Rounds down to 1.
        // offset to line 1 = 5 + 1 = 6. Final = 6 + 1 = 7.
        assert_eq!(result, 7);
        // Verify result is a valid char boundary by slicing
        let _ = &input[..result];
    }

    #[test]
    fn cursor_up_multibyte_to_ascii_rounds_down() {
        // "a─\nabcde" — line 0 is 4 bytes (a(1) + ─(3)), line 1 is 5 bytes
        // Cursor at byte 8 in line 1 ('d', col=2). Up should land at byte 2 in line 0,
        // which is inside ─ (bytes 1..4). Should round down to byte 1 (after 'a').
        let input = "a─\nabcde";
        let result = cursor_up(input, 8); // pos 8 = line 1, col 2
        // Byte 2 in line 0 is inside '─'. Should round down to 1 (after 'a').
        assert_eq!(result, 1);
        let _ = &input[..result];
    }

    #[test]
    fn cursor_down_multibyte_to_wider_multibyte() {
        // "öäü\n😀" — line 0 = 6 bytes (ö(2) + ä(2) + ü(2)), line 1 = 4 bytes (😀)
        // Cursor at byte 5 in line 0 (inside ü, bytes 4..6). Down to line 1.
        // col=5.min(4)=4, rounds to 4 (end of line 1).
        let input = "öäü\n😀";
        let result = cursor_down(input, 5);
        // offset to line 1 = 6 + 1 = 7. Final = 7 + 4 = 11.
        assert_eq!(result, 11);
        let _ = &input[..result];
    }

    #[test]
    fn cursor_up_multibyte_to_wider_multibyte() {
        // "😀\nöäü" — line 0 = 4 bytes (😀), line 1 = 6 bytes
        // Cursor at byte 12 (past end, clamped to 11 = end of line 1, col=6).
        // Up to line 0: col=6.min(4)=4, rounds to 4 (end of line 0).
        let input = "😀\nöäü";
        let result = cursor_up(input, 12);
        assert_eq!(result, 4);
        let _ = &input[..result];
    }

    #[test]
    fn cursor_down_into_box_drawing_chars() {
        // Reproduce the exact panic scenario: pasting box-drawing characters
        // "hello\n┌────┐" — line 0 = 5 bytes, line 1 = 18 bytes (┌(3) + ─(3)*4 + ┐(3))
        // Cursor at byte 1 in line 0 ('e'). Down lands at byte 1 in line 1,
        // which is inside ┌ (bytes 0..3). Should round down to 0.
        let input = "hello\n┌────┐";
        let result = cursor_down(input, 1);
        // offset to line 1 = 5 + 1 = 6. Byte 1 rounds down to 0.
        assert_eq!(result, 6);
        let _ = &input[..result];
    }

    #[test]
    fn cursor_up_from_ascii_into_box_drawing() {
        // "┌────┐\nhello" — line 0 has box chars, line 1 is ASCII
        // Cursor at byte 22 in line 1 ('l', col=3). Up lands at byte 3 in line 0.
        // Byte 3 is the start of the first '─' (┌=0..3, ─=3..6). This IS a boundary.
        let input = "┌────┐\nhello";
        let result = cursor_up(input, 22);
        assert_eq!(result, 3);
        let _ = &input[..result];
    }

    #[test]
    fn cursor_up_from_ascii_into_box_drawing_mid_char() {
        // Same layout but cursor at byte 21 in line 1 ('e', col=1).
        // Up lands at byte 1 in line 0, which IS inside ┌ (bytes 0..3). Rounds down to 0.
        let input = "┌────┐\nhello";
        let result = cursor_up(input, 21);
        assert_eq!(result, 0);
        let _ = &input[..result];
    }

    // ---------------------------------------------------------------------------
    // display_width_to_byte_offset
    // ---------------------------------------------------------------------------

    #[test]
    fn display_width_to_byte_offset_ascii() {
        assert_eq!(display_width_to_byte_offset("hello", 0), 0);
        assert_eq!(display_width_to_byte_offset("hello", 2), 2);
        assert_eq!(display_width_to_byte_offset("hello", 5), 5);
        assert_eq!(display_width_to_byte_offset("hello", 10), 5); // exceeds length
    }

    #[test]
    fn display_width_to_byte_offset_multibyte() {
        // "öäü" = 6 bytes, 3 display cols (each char is width 1)
        assert_eq!(display_width_to_byte_offset("öäü", 0), 0);
        assert_eq!(display_width_to_byte_offset("öäü", 1), 2); // after ö
        assert_eq!(display_width_to_byte_offset("öäü", 2), 4); // after ä
        assert_eq!(display_width_to_byte_offset("öäü", 3), 6); // end
    }

    #[test]
    fn display_width_to_byte_offset_emoji() {
        // "😀a" = 5 bytes, 3 display cols (😀=2, a=1)
        assert_eq!(display_width_to_byte_offset("😀a", 0), 0);
        assert_eq!(display_width_to_byte_offset("😀a", 2), 4); // after 😀
        assert_eq!(display_width_to_byte_offset("😀a", 3), 5); // end
    }

    #[test]
    fn display_width_to_byte_offset_empty() {
        assert_eq!(display_width_to_byte_offset("", 0), 0);
        assert_eq!(display_width_to_byte_offset("", 5), 0);
    }

    #[test]
    fn display_width_to_byte_offset_box_drawing() {
        // "┌────┐" = 15 bytes, 5 display cols
        assert_eq!(display_width_to_byte_offset("┌────┐", 0), 0);
        assert_eq!(display_width_to_byte_offset("┌────┐", 1), 3); // after ┌
        assert_eq!(display_width_to_byte_offset("┌────┐", 3), 9); // after 2nd ─
        assert_eq!(display_width_to_byte_offset("┌────┐", 5), 15); // end
    }

    // ---------------------------------------------------------------------------
    // cursor_up_visual / cursor_down_visual
    // ---------------------------------------------------------------------------

    #[test]
    fn cursor_up_visual_single_line_noop() {
        // "hello" with wrap_width 20 → 1 visual line. Up is no-op, returns unchanged.
        let input = "hello";
        assert_eq!(cursor_up_visual(input, 0, 20), 0);
        assert_eq!(cursor_up_visual(input, 3, 20), 3);
        assert_eq!(cursor_up_visual(input, 5, 20), 5);
    }

    #[test]
    fn cursor_down_visual_single_line_noop() {
        // "hello" with wrap_width 20 → 1 visual line. Down is no-op, returns unchanged.
        let input = "hello";
        assert_eq!(cursor_down_visual(input, 0, 20), 0);
        assert_eq!(cursor_down_visual(input, 3, 20), 3);
        assert_eq!(cursor_down_visual(input, 5, 20), 5);
    }

    #[test]
    fn cursor_up_visual_wrapped_line() {
        // "hello world" wrapped at 5 → 3 visual lines
        // Vis 0: "hello" (0-5), Vis 1: " worl" (5-10), Vis 2: "d" (10-11)
        // Cursor at byte 7 ('o' in "worl") → vis line 1. Up → vis line 0, col 2.
        let input = "hello world";
        let result = cursor_up_visual(input, 7, 5);
        // vis line 0, col 2 → byte 2
        assert_eq!(result, 2);
    }

    #[test]
    fn cursor_down_visual_wrapped_line() {
        // "hello world" wrapped at 5 → 3 visual lines
        // Cursor at byte 2 ('l' in "hello") → vis line 0, col 2.
        // Down → vis line 1 (" worl"), col 2 → byte 7
        let input = "hello world";
        let result = cursor_down_visual(input, 2, 5);
        assert_eq!(result, 7);
    }

    #[test]
    fn cursor_up_visual_multiline() {
        let input = "abc\nhello world";
        // Line 0: "abc" → 1 visual line
        // Line 1: "hello world" → 3 visual lines at width 5
        // Cursor at byte 8 ('l' in "hello") → vis line 1. Up → vis line 0 ("abc"), col clamped to 3.
        let result = cursor_up_visual(input, 8, 5);
        assert_eq!(result, 3);
    }

    #[test]
    fn cursor_down_visual_multiline() {
        let input = "hello world\nabc";
        // Line 0: "hello world" → 3 visual lines at width 5
        // Line 1: "abc" → 1 visual line
        // Cursor at byte 7 ('o' in "worl") → vis line 1, col 3.
        // Down → vis line 2 ("d"), col clamped to 1 → byte 11
        let result = cursor_down_visual(input, 7, 5);
        assert_eq!(result, 11);
    }

    #[test]
    fn cursor_up_visual_at_top_returns_unchanged() {
        let input = "hello world";
        // Cursor at byte 0 → vis line 0. Up returns unchanged.
        assert_eq!(cursor_up_visual(input, 0, 5), 0);
        // Cursor at byte 3 → vis line 0. Up returns unchanged.
        assert_eq!(cursor_up_visual(input, 3, 5), 3);
    }

    #[test]
    fn cursor_down_visual_at_bottom_returns_unchanged() {
        let input = "hello world";
        // Cursor at byte 11 (past end, clamped) → vis line 2 (last). Down returns unchanged.
        assert_eq!(cursor_down_visual(input, 11, 5), 11);
        // Cursor at byte 10 ('d') → vis line 1 (because byte 10 falls in seg (5,10)). Not at bottom.
        // Down → vis line 2 ("d"), col clamped to 1 → byte 11
        assert_eq!(cursor_down_visual(input, 10, 5), 11);
    }

    #[test]
    fn cursor_up_visual_empty_input() {
        assert_eq!(cursor_up_visual("", 0, 10), 0);
    }

    #[test]
    fn cursor_down_visual_empty_input() {
        assert_eq!(cursor_down_visual("", 0, 10), 0);
    }

    #[test]
    fn cursor_up_visual_zero_wrap_width() {
        assert_eq!(cursor_up_visual("hello", 2, 0), 2);
    }

    #[test]
    fn cursor_down_visual_zero_wrap_width() {
        assert_eq!(cursor_down_visual("hello", 2, 0), 2);
    }

    #[test]
    fn cursor_up_visual_multibyte_wrapped() {
        // "öäüöäü" = 12 bytes, 6 display cols. Width 2 → 3 visual lines.
        // Vis 0: "öä" (0-4), Vis 1: "üö" (4-8), Vis 2: "äü" (8-12)
        // Cursor at byte 6 ('ö' in Vis 1) → vis line 1, col 1.
        // Up → vis line 0 ("öä"), col 1 → byte 2
        let input = "öäüöäü";
        let result = cursor_up_visual(input, 6, 2);
        assert_eq!(result, 2);
    }

    #[test]
    fn cursor_down_visual_multibyte_wrapped() {
        // "öäüöäü" = 12 bytes, 6 display cols. Width 2 → 3 visual lines.
        // Cursor at byte 2 ('ä' in Vis 0) → vis line 0, col 1.
        // Down → vis line 1 ("üö"), col 1 → byte 6
        let input = "öäüöäü";
        let result = cursor_down_visual(input, 2, 2);
        assert_eq!(result, 6);
    }

    #[test]
    fn cursor_up_visual_wide_to_narrow_segment() {
        // "😀😀\nab" — line 0 has 2 emoji (4 display cols), line 1 has 2 ASCII chars
        // Width 3: line 0 → 2 visual lines (😀, 😀), line 1 → 1 visual line (ab)
        // Cursor at byte 4 (second 😀) → vis line 1, col 2 (emoji width 2).
        // Up → vis line 0 (first 😀), col clamped to 2 → byte 4 (end of first 😀)
        let input = "😀😀\nab";
        let result = cursor_up_visual(input, 4, 3);
        assert_eq!(result, 4);
    }

    #[test]
    fn cursor_down_visual_crosses_logical_line() {
        // "ab\nhello world" — line 0: "ab", line 1: "hello world"
        // Width 5: line 0 → 1 vis line, line 1 → 3 vis lines
        // Cursor at byte 2 (end of "ab") → vis line 0, col 2.
        // Down → vis line 1 ("hello"), col 2 → byte 5
        let input = "ab\nhello world";
        let result = cursor_down_visual(input, 2, 5);
        assert_eq!(result, 5);
    }
