// Extracted tests from src/tui/editor/discovery.rs
// Auto-generated by extract-tests.sh

use super::{FileDiscovery, FileMatch};
use std::fs;
use tempfile::TempDir;

    fn mk_file(path: &str) -> FileMatch {
        FileMatch { path: path.to_string(), is_directory: false }
    }

    fn mk_dir(path: &str) -> FileMatch {
        FileMatch { path: path.to_string(), is_directory: true }
    }

    // ---------------------------------------------------------------------------
    // FileMatch
    // ---------------------------------------------------------------------------

    #[test]
    fn file_match_icon_file() {
        let m = mk_file("src/main.rs");
        assert_eq!(m.icon(), "📄");
    }

    #[test]
    fn file_match_icon_directory() {
        let m = mk_dir("src/tui/");
        assert_eq!(m.icon(), "📁");
    }

    #[test]
    fn file_match_display() {
        let m = mk_file("src/main.rs");
        assert_eq!(m.display(), "📄 src/main.rs");
    }

    #[test]
    fn file_match_display_directory() {
        let m = mk_dir("src/tui/");
        assert_eq!(m.display(), "📁 src/tui/");
    }

    // ---------------------------------------------------------------------------
    // Fuzzy match
    // ---------------------------------------------------------------------------

    #[test]
    fn fuzzy_match_empty_query_returns_all() {
        let entries = vec![mk_file("a.rs"), mk_file("b.txt"), mk_file("c.py")];
        let results = FileDiscovery::fuzzy_match(&entries, "", 2, true);
        assert_eq!(results.len(), 2);
        assert_eq!(results[0].path, "a.rs");
        assert_eq!(results[1].path, "b.txt");
    }

    #[test]
    fn fuzzy_match_exact() {
        let entries = vec![mk_file("src/main.rs"), mk_file("src/lib.rs")];
        let results = FileDiscovery::fuzzy_match(&entries, "main.rs", 5, true);
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].path, "src/main.rs");
    }

    #[test]
    fn fuzzy_match_partial() {
        let entries = vec![mk_file("src/main.rs"), mk_file("src/lib.rs"), mk_file("Cargo.toml")];
        let results = FileDiscovery::fuzzy_match(&entries, "mnr", 5, true);
        // "mnr" fuzzy matches "main.rs" (m-a-i-n → m, n)
        assert!(!results.is_empty());
        assert!(results.iter().any(|f| f.path.contains("main")));
    }

    #[test]
    fn fuzzy_match_case_insensitive() {
        let entries = vec![mk_file("README.md"), mk_file("readme.txt")];
        let results = FileDiscovery::fuzzy_match(&entries, "readme", 5, true);
        assert_eq!(results.len(), 2);
    }

    #[test]
    fn fuzzy_match_respects_max_results() {
        let entries: Vec<FileMatch> = (0..10).map(|i| mk_file(&format!("file{i}.rs"))).collect();
        let results = FileDiscovery::fuzzy_match(&entries, "", 3, true);
        assert!(results.len() <= 3);
    }

    #[test]
    fn fuzzy_match_no_results() {
        let entries = vec![mk_file("a.rs"), mk_file("b.txt")];
        let results = FileDiscovery::fuzzy_match(&entries, "xyz", 5, true);
        assert!(results.is_empty());
    }

    #[test]
    fn fuzzy_match_sorted_by_score() {
        let entries = vec![mk_file("main.rs"), mk_file("lib.rs"), mk_file("m.rs")];
        let results = FileDiscovery::fuzzy_match(&entries, "m", 5, true);
        // All match "m" but "m.rs" has consecutive bonus (exact single char)
        assert!(!results.is_empty());
    }

    #[test]
    fn fuzzy_match_path_components() {
        let entries = vec![mk_file("src/ui/theme.rs"), mk_file("src/core/engine.rs")];
        let results = FileDiscovery::fuzzy_match(&entries, "theme", 5, true);
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].path, "src/ui/theme.rs");
    }

    #[test]
    fn fuzzy_match_preserves_directory_type() {
        let entries = vec![mk_dir("src/tui/"), mk_file("src/tui/app.rs")];
        let results = FileDiscovery::fuzzy_match(&entries, "tui", 5, true);
        assert_eq!(results.len(), 2);
        assert!(results[0].is_directory);
        assert!(!results[1].is_directory);
    }

    #[test]
    fn fuzzy_match_slider_in_nested_path() {
        let entries = vec![
            mk_file("src/components/slider.rs"),
            mk_file("src/tui/app.rs"),
            mk_file("README.md"),
        ];
        // "slide" should match slider.rs
        let results = FileDiscovery::fuzzy_match(&entries, "slide", 10, true);
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].path, "src/components/slider.rs");

        // "slider" should also match slider.rs
        let results = FileDiscovery::fuzzy_match(&entries, "slider", 10, true);
        assert_eq!(
            results.len(),
            1,
            "Expected 'slider' to match 'src/components/slider.rs', got {} results",
            results.len()
        );
        assert_eq!(results[0].path, "src/components/slider.rs");

        // "sli" should also match slider.rs (s-l-i are in order in "slider")
        let results = FileDiscovery::fuzzy_match(&entries, "sli", 10, true);
        assert_eq!(
            results.len(),
            1,
            "Expected 'sli' to match 'src/components/slider.rs', got {} results",
            results.len()
        );
        assert_eq!(results[0].path, "src/components/slider.rs");

        // "sl" should also match slider.rs
        let results = FileDiscovery::fuzzy_match(&entries, "sl", 10, true);
        assert_eq!(
            results.len(),
            1,
            "Expected 'sl' to match 'src/components/slider.rs', got {} results",
            results.len()
        );
        assert_eq!(results[0].path, "src/components/slider.rs");
    }

    // ---------------------------------------------------------------------------
    // Simulate full @ autocomplete typing flow
    // ---------------------------------------------------------------------------

    #[test]
    fn autocomplete_typing_flow_sl_then_sli() {
        // Simulate user typing @sl then continuing to @sli
        use crate::tui::autocomplete::get_query_after_char;

        let entries = vec![
            mk_file("src/components/slider.rs"),
            mk_file("src/slice_util.rs"),
            mk_file("src/tui/app.rs"),
            mk_file("README.md"),
        ];

        // Step 1: User types @ — query is empty, all files shown
        let input = "@";
        let query = get_query_after_char(input, '@');
        assert_eq!(query, "");
        let results = FileDiscovery::fuzzy_match(&entries, &query, 100, true);
        assert_eq!(results.len(), 4, "Empty query should return all files");

        // Step 2: User types s — query is "s"
        let input = "@s";
        let query = get_query_after_char(input, '@');
        assert_eq!(query, "s");
        let results = FileDiscovery::fuzzy_match(&entries, &query, 100, true);
        assert!(!results.is_empty(), "'s' should match some files");
        assert!(
            results.iter().any(|f| f.path.contains("slider")),
            "'s' should match slider.rs"
        );

        // Step 3: User types l — query is "sl"
        let input = "@sl";
        let query = get_query_after_char(input, '@');
        assert_eq!(query, "sl");
        let results = FileDiscovery::fuzzy_match(&entries, &query, 100, true);
        assert!(!results.is_empty(), "'sl' should match some files");
        assert!(
            results.iter().any(|f| f.path.contains("slider")),
            "'sl' should match slider.rs, got: {:?}",
            results.iter().map(|f| &f.path).collect::<Vec<_>>()
        );

        // Step 4: User types i — query is "sli"
        // THIS IS THE BUG: popup goes empty even though "sli" matches "slider.rs"
        let input = "@sli";
        let query = get_query_after_char(input, '@');
        assert_eq!(query, "sli");
        let results = FileDiscovery::fuzzy_match(&entries, &query, 100, true);
        assert!(
            !results.is_empty(),
            "BUG: 'sli' should match slider.rs and slice_util.rs, got {} results",
            results.len()
        );
        assert!(
            results.iter().any(|f| f.path.contains("slider")),
            "BUG: 'sli' should match slider.rs, got: {:?}",
            results.iter().map(|f| &f.path).collect::<Vec<_>>()
        );
    }

    // ---------------------------------------------------------------------------
    // Front-truncation
    // ---------------------------------------------------------------------------

    #[test]
    fn display_truncated_short_path_no_truncation() {
        let m = mk_file("src/main.rs");
        assert_eq!(m.display_truncated(80), "📄 src/main.rs");
    }

    #[test]
    fn display_truncated_long_path() {
        let m = mk_file("src/components/ui/widgets/slider.rs");
        let result = m.display_truncated(25);
        assert!(result.starts_with("📄"));
        assert!(result.contains("…"));
        assert!(result.ends_with("slider.rs"));
    }

    #[test]
    fn display_truncated_preserves_filename() {
        let m = mk_file("a/very/deeply/nested/path/to/some/file_name.rs");
        let result = m.display_truncated(30);
        assert!(result.ends_with("file_name.rs"));
        assert!(result.contains("…"));
    }

    #[test]
    fn display_truncated_directory_icon() {
        let m = mk_dir("src/components/ui/widgets/");
        let result = m.display_truncated(25);
        assert!(result.starts_with("📁"));
        assert!(result.contains("…"));
    }

    // ---------------------------------------------------------------------------
    // Hidden file detection
    // ---------------------------------------------------------------------------

    #[test]
    fn is_hidden_dotfile() {
        let m = mk_file(".env");
        assert!(m.is_hidden());
    }

    #[test]
    fn is_hidden_dotdir() {
        let m = mk_dir(".vscode/");
        assert!(m.is_hidden());
    }

    #[test]
    fn is_hidden_nested_in_dotdir() {
        let m = mk_file(".vscode/settings.json");
        assert!(m.is_hidden());
    }

    #[test]
    fn is_hidden_not_hidden() {
        let m = mk_file("src/main.rs");
        assert!(!m.is_hidden());
    }

    #[test]
    fn is_hidden_regular_dir_with_dot_in_name() {
        // "my.dir" starts with "my" not "."
        let m = mk_dir("my.dir/");
        assert!(!m.is_hidden());
    }

    // ---------------------------------------------------------------------------
    // Hidden filter in fuzzy_match
    // ---------------------------------------------------------------------------

    #[test]
    fn fuzzy_match_hides_hidden_files() {
        let entries = vec![
            mk_file("src/main.rs"),
            mk_file(".env"),
            mk_file(".gitignore"),
            mk_dir(".vscode/"),
            mk_file("src/lib.rs"),
        ];
        let results = FileDiscovery::fuzzy_match(&entries, "", 100, false);
        assert_eq!(results.len(), 2);
        assert_eq!(results[0].path, "src/lib.rs");
        assert_eq!(results[1].path, "src/main.rs");
    }

    #[test]
    fn fuzzy_match_shows_hidden_files() {
        let entries = vec![
            mk_file("src/main.rs"),
            mk_file(".env"),
            mk_file(".gitignore"),
            mk_dir(".vscode/"),
            mk_file("src/lib.rs"),
        ];
        let results = FileDiscovery::fuzzy_match(&entries, "", 100, true);
        assert_eq!(results.len(), 5);
    }

    #[test]
    fn fuzzy_match_hidden_filter_with_query() {
        let entries = vec![
            mk_file("src/main.rs"),
            mk_file(".env"),
            mk_file("src/lib.rs"),
        ];
        // Query "env" matches .env, but hidden filter removes it
        let results = FileDiscovery::fuzzy_match(&entries, "env", 100, false);
        assert!(results.is_empty());
    }

    // ---------------------------------------------------------------------------
    // discover_entries: always-visible (force-include) patterns
    // ---------------------------------------------------------------------------

    /// Build a temp project layout:
    ///
    /// ```text
    /// .gitignore            (content passed by the test)
    /// docs/plans/design.md
    /// docs/plans/notes/inner.md
    /// src/main.rs
    /// target/build.txt
    /// ```
    fn fixture_project(gitignore: &str) -> (TempDir, std::path::PathBuf) {
        let dir = TempDir::new().unwrap();
        let root = dir.path().to_path_buf();

        fs::write(root.join(".gitignore"), gitignore).unwrap();
        fs::create_dir_all(root.join("docs/plans/notes")).unwrap();
        fs::write(root.join("docs/plans/design.md"), "plan").unwrap();
        fs::write(root.join("docs/plans/notes/inner.md"), "notes").unwrap();
        fs::create_dir_all(root.join("src")).unwrap();
        fs::write(root.join("src/main.rs"), "fn main() {}").unwrap();
        fs::create_dir_all(root.join("target")).unwrap();
        fs::write(root.join("target/build.txt"), "artifact").unwrap();

        (dir, root)
    }

    fn paths_of(entries: &[FileMatch]) -> Vec<&str> {
        entries.iter().map(|e| e.path.as_str()).collect()
    }

    #[test]
    fn discover_entries_hides_gitignored_dir_and_children() {
        let (_dir, root) = fixture_project("docs/plans/\n");
        let entries = FileDiscovery::discover_entries(&root, &[]);
        let paths = paths_of(&entries);
        assert!(!paths.contains(&"docs/plans"), "gitignored dir must be hidden");
        assert!(!paths.contains(&"docs/plans/design.md"), "child of gitignored dir must be hidden");
        assert!(!paths.contains(&"docs/plans/notes"), "nested child dir must be hidden");
        assert!(!paths.contains(&"docs/plans/notes/inner.md"), "nested child file must be hidden");
    }

    #[test]
    fn discover_entries_force_includes_listed_gitignored_dir() {
        let (_dir, root) = fixture_project("docs/plans/\n");
        let patterns = vec!["docs/plans/".to_string()];
        let entries = FileDiscovery::discover_entries(&root, &patterns);
        let paths = paths_of(&entries);
        assert!(paths.contains(&"docs/plans"), "force-included dir must be visible");
        assert!(paths.contains(&"docs/plans/design.md"), "child file must be visible");
        assert!(paths.contains(&"docs/plans/notes"), "nested child dir must be visible");
        assert!(paths.contains(&"docs/plans/notes/inner.md"), "nested child file must be visible");
    }

    #[test]
    fn discover_entries_empty_always_visible_restores_baseline() {
        let (_dir, root) = fixture_project("docs/plans/\ndocs/reviews/\n");
        let entries = FileDiscovery::discover_entries(&root, &[]);
        let paths = paths_of(&entries);
        // Empty list opts out: every gitignored path stays hidden
        assert!(!paths.contains(&"docs/plans"));
        assert!(!paths.contains(&"docs/plans/design.md"));
    }

    #[test]
    fn discover_entries_non_gitignored_path_unaffected_by_list() {
        let (_dir, root) = fixture_project("docs/plans/\n");
        for patterns in [&[] as &[String], &["docs/plans/".to_string()], &["nonexistent/".to_string()]] {
            let entries = FileDiscovery::discover_entries(&root, patterns);
            let paths = paths_of(&entries);
            assert!(paths.contains(&"src"), "non-gitignored dir must stay visible");
            assert!(paths.contains(&"src/main.rs"), "non-gitignored file must stay visible");
        }
    }

    #[test]
    fn discover_entries_noise_dir_stays_excluded_even_if_listed() {
        let (_dir, root) = fixture_project("target/\n");
        let patterns = vec!["target/".to_string()];
        let entries = FileDiscovery::discover_entries(&root, &patterns);
        let paths = paths_of(&entries);
        assert!(!paths.contains(&"target"), "hard noise-dir exclusion cannot be force-included");
        assert!(!paths.contains(&"target/build.txt"), "child of noise dir must stay hidden");
    }
