// Extracted tests from src/tui/editor/wrap.rs
// Auto-generated by extract-tests.sh

use super::wrap::{build_visual_lines, cursor_visual_pos, last_char_boundary, wrap_line};

    // -----------------------------------------------------------------------
    // wrap_line
    // -----------------------------------------------------------------------

    #[test]
    fn wrap_line_short() {
        let segments = wrap_line("hello", 20);
        assert_eq!(segments, vec![(0, 5)]);
    }

    #[test]
    fn wrap_line_exact_width() {
        let segments = wrap_line("hello", 5);
        assert_eq!(segments, vec![(0, 5)]);
    }

    #[test]
    fn wrap_line_over_width() {
        // "hello world" = 11 chars, wrap at 5
        // Segments: "hello" (0-5), " worl" (5-10), "d" (10-11)
        let segments = wrap_line("hello world", 5);
        assert_eq!(segments.len(), 3);
        assert_eq!(segments[0], (0, 5));
        assert_eq!(segments[1], (5, 10));
        assert_eq!(segments[2], (10, 11));
    }

    #[test]
    fn wrap_line_empty() {
        let segments = wrap_line("", 10);
        assert_eq!(segments, vec![(0, 0)]);
    }

    #[test]
    fn wrap_line_zero_width() {
        let segments = wrap_line("hello", 0);
        assert!(segments.is_empty());
    }

    #[test]
    fn wrap_line_wide_chars() {
        // "你好" = 2 chars, each width 2 = 4 display cols
        let segments = wrap_line("你好", 3);
        assert_eq!(segments.len(), 2);
        assert_eq!(segments[0], (0, 3)); // "你" (width 2, fits in 3)
        assert_eq!(segments[1], (3, 6)); // "好" (width 2, new segment)
    }

    #[test]
    fn wrap_line_wide_chars_fit() {
        let segments = wrap_line("你好", 4);
        assert_eq!(segments, vec![(0, 6)]);
    }

    #[test]
    fn wrap_line_three_segments() {
        // "abc def ghi" = 11 chars, wrap at 4
        // Segments: "abc " (0-4), "def " (4-8), "ghi" (8-11)
        let segments = wrap_line("abc def ghi", 4);
        assert_eq!(segments.len(), 3);
        assert_eq!(segments[0], (0, 4)); // "abc "
        assert_eq!(segments[1], (4, 8)); // "def "
        assert_eq!(segments[2], (8, 11)); // "ghi"
    }

    #[test]
    fn wrap_line_segments_are_char_boundaries() {
        // "héllo" = h(1) é(1) l(1) l(1) o(1) = 5 display cols, 6 bytes
        let segments = wrap_line("héllo", 3);
        assert_eq!(segments.len(), 2);
        // Verify segments don't split é (2-byte char)
        for &(start, end) in &segments {
            // Each segment should be valid UTF-8
            let _seg: &str = &"héllo"[start..end];
        }
    }

    // -----------------------------------------------------------------------
    // build_visual_lines
    // -----------------------------------------------------------------------

    #[test]
    fn build_visual_lines_single_short_line() {
        let lines = build_visual_lines("hello", 20);
        assert_eq!(lines, vec![(0, 0, 5)]);
    }

    #[test]
    fn build_visual_lines_multiline() {
        let lines = build_visual_lines("abc\ndef", 20);
        assert_eq!(lines.len(), 2);
        assert_eq!(lines[0], (0, 0, 3));
        assert_eq!(lines[1], (1, 0, 3));
    }

    #[test]
    fn build_visual_lines_wraps_long_line() {
        let input = "short\nthis is a very long line that needs wrapping";
        let lines = build_visual_lines(input, 10);
        // Line 0: "short" → 1 visual line
        // Line 1: long → multiple visual lines
        assert_eq!(lines[0].0, 0); // logical line 0
        assert_eq!(lines[1].0, 1); // logical line 1
        assert!(lines.len() > 2); // at least 3 visual lines total
    }

    // -----------------------------------------------------------------------
    // cursor_visual_pos
    // -----------------------------------------------------------------------

    #[test]
    fn cursor_visual_pos_single_line_no_wrap() {
        let (vl, vc) = cursor_visual_pos("hello", 3, 20);
        assert_eq!(vl, 0);
        assert_eq!(vc, 3);
    }

    #[test]
    fn cursor_visual_pos_wrapped_line() {
        // "hello world" wrapped at 5
        // Visual line 0: "hello" (0-5)
        // Visual line 1: " worl" (5-10)
        // Visual line 2: "d" (10-11)
        // Cursor at byte 7 ('o' in "worl") → logical line 0, col 7
        // Falls in seg (5,10), vis_line = 0+1 = 1, vis_col = width(" wo") = 2
        let (vl, vc) = cursor_visual_pos("hello world", 7, 5);
        assert_eq!(vl, 1);
        assert_eq!(vc, 2);
    }

    #[test]
    fn cursor_visual_pos_at_wrap_boundary() {
        // "hello world" wrapped at 5
        // Cursor at byte 5 (the space) → col_in_line=5, falls in seg (0,5), vis_col=5
        let (vl, vc) = cursor_visual_pos("hello world", 5, 5);
        assert_eq!(vl, 0);
        assert_eq!(vc, 5);
    }

    #[test]
    fn cursor_visual_pos_multiline() {
        let input = "abc\nhello world";
        // Line 0: "abc" → 1 visual line
        // Line 1: "hello world" → 3 visual lines at width 5
        // Cursor at byte 8 ('l' in "hello") → logical line 1, col 4
        // "hello world" segs: (0,5), (5,10), (10,11)
        // col 4 → seg (0,5), vis_line = 1 + 0 = 1, vis_col = width("hell") = 4
        let (vl, vc) = cursor_visual_pos(input, 8, 5);
        assert_eq!(vl, 1);
        assert_eq!(vc, 4);
    }

    #[test]
    fn cursor_visual_pos_end_of_wrapped_line() {
        // "hello world" at end (byte 11)
        // Segs: (0,5), (5,10), (10,11) → 3 visual lines
        // col 11 → seg (10,11), vis_line = 2, vis_col = width("d") = 1
        let (vl, vc) = cursor_visual_pos("hello world", 11, 5);
        assert_eq!(vl, 2);
        assert_eq!(vc, 1);
    }

    #[test]
    fn cursor_visual_pos_start() {
        let (vl, vc) = cursor_visual_pos("hello world", 0, 5);
        assert_eq!(vl, 0);
        assert_eq!(vc, 0);
    }

    #[test]
    fn cursor_visual_pos_empty_input() {
        let (vl, vc) = cursor_visual_pos("", 0, 10);
        assert_eq!(vl, 0);
        assert_eq!(vc, 0);
    }

    // -----------------------------------------------------------------------
    // Regression: cursor_visual_pos must handle mid-char positions gracefully
    // -----------------------------------------------------------------------

    #[test]
    fn cursor_visual_pos_mid_char_does_not_panic() {
        // Simulate cursor_down landing inside a multi-byte character.
        // "a─" = a(1) + ─(3) = 4 bytes. Byte 3 is inside ─ (bytes 1..4).
        // This should NOT panic — should round down to byte 1 (after 'a').
        let (vl, vc) = cursor_visual_pos("a─", 3, 10);
        // Rounds to byte 1, so vis_col = width("a") = 1
        assert_eq!(vl, 0);
        assert_eq!(vc, 1);
    }

    #[test]
    fn cursor_visual_pos_multiline_mid_char_does_not_panic() {
        // "hello\na─" — cursor at byte 6+3=9 which is inside ─ in line 1.
        // Line 1: "a─", col_in_line = 3 (inside ─ at bytes 1..4).
        // Should round down to byte 1 (after 'a').
        let (vl, vc) = cursor_visual_pos("hello\na─", 9, 20);
        // Line 0 = 1 visual line. Line 1 = 1 visual line. vl = 1.
        // Rounds to byte 1, vis_col = width("a") = 1
        assert_eq!(vl, 1);
        assert_eq!(vc, 1);
    }

    #[test]
    fn cursor_visual_pos_box_drawing_paste() {
        // Reproduce exact panic scenario: pasted box-drawing characters
        // "┌────┐" = 7 bytes (┌(3) + ─(3) + ─(3) + ─(3) + ┐(3) = 15 bytes)
        // Cursor at byte 3 (start of second ─). This IS a boundary, should work fine.
        let (vl, vc) = cursor_visual_pos("┌────┐", 3, 20);
        assert_eq!(vl, 0);
        // ┌ has width 1, so vis_col = 1
        assert_eq!(vc, 1);
    }

    #[test]
    fn cursor_visual_pos_box_drawing_mid_char() {
        // "┌────┐" — cursor at byte 2 (inside ─ at bytes 0..3).
        // Should round down to 0.
        let (vl, vc) = cursor_visual_pos("┌────┐", 2, 20);
        assert_eq!(vl, 0);
        assert_eq!(vc, 0);
    }

    // -----------------------------------------------------------------------
    // last_char_boundary
    // -----------------------------------------------------------------------

    #[test]
    fn last_char_boundary_ascii() {
        assert_eq!(last_char_boundary("hello", 0), 0);
        assert_eq!(last_char_boundary("hello", 1), 1);
        assert_eq!(last_char_boundary("hello", 5), 5);
        assert_eq!(last_char_boundary("hello", 100), 5); // clamped
    }

    #[test]
    fn last_char_boundary_mid_multibyte() {
        // "a─" = a(1) + ─(3) = 4 bytes
        assert_eq!(last_char_boundary("a─", 0), 0);
        assert_eq!(last_char_boundary("a─", 1), 1); // after 'a'
        assert_eq!(last_char_boundary("a─", 2), 1); // inside ─, rounds to 1
        assert_eq!(last_char_boundary("a─", 3), 1); // inside ─, rounds to 1
        assert_eq!(last_char_boundary("a─", 4), 4); // end
    }

    #[test]
    fn last_char_boundary_emoji() {
        // "a😀b" = a(1) + 😀(4) + b(1) = 6 bytes
        assert_eq!(last_char_boundary("a😀b", 0), 0);
        assert_eq!(last_char_boundary("a😀b", 1), 1); // after 'a'
        assert_eq!(last_char_boundary("a😀b", 2), 1); // inside 😀, rounds to 1
        assert_eq!(last_char_boundary("a😀b", 3), 1); // inside 😀, rounds to 1
        assert_eq!(last_char_boundary("a😀b", 4), 1); // inside 😀, rounds to 1
        assert_eq!(last_char_boundary("a😀b", 5), 5); // after 😀
        assert_eq!(last_char_boundary("a😀b", 6), 6); // end
    }

    #[test]
    fn last_char_boundary_empty() {
        assert_eq!(last_char_boundary("", 0), 0);
        assert_eq!(last_char_boundary("", 5), 0);
    }
