// Extracted tests from src/agent/token_estimation.rs
// Auto-generated by extract-tests.sh

use super::token_estimation::{approx_token_count, estimate_tokens_from_messages, estimate_tokens_from_streamed_text};
use crate::session::AgentMessage;

    #[test]
    fn approx_token_count_empty() {
        assert_eq!(approx_token_count(""), 0);
    }

    #[test]
    fn approx_token_count_rounds_up() {
        // "hi" = 2 chars → (2+3)/4 = 1
        assert_eq!(approx_token_count("hi"), 1);
        // "hello" = 5 chars → (5+3)/4 = 2
        assert_eq!(approx_token_count("hello"), 2);
        // 100 chars → 25
        assert_eq!(approx_token_count(&"a".repeat(100)), 25);
    }

    #[test]
    fn estimate_tokens_from_messages_empty() {
        assert_eq!(estimate_tokens_from_messages(&[]), 0);
    }

    #[test]
    fn estimate_tokens_from_messages_user() {
        let msg = AgentMessage::user("hello".to_string());
        let tokens = estimate_tokens_from_messages(&[msg]);
        // "user" (1) + "hello" (2) = 3
        assert_eq!(tokens, 3);
    }

    #[test]
    fn estimate_tokens_from_messages_system() {
        let msg = AgentMessage::system("You are an AI".to_string());
        let tokens = estimate_tokens_from_messages(&[msg]);
        // "system" = 6 chars → (6+3)/4 = 2
        // "You are an AI" = 13 chars → (13+3)/4 = 4
        // Total = 6
        assert_eq!(tokens, 6);
    }

    #[test]
    fn estimate_tokens_from_streamed_text_test() {
        assert_eq!(estimate_tokens_from_streamed_text(""), 0);
        assert_eq!(estimate_tokens_from_streamed_text("hello world"), 3); // 11 chars → (11+3)/4 = 3
    }
