// Extracted tests from src/session/compaction.rs
// Auto-generated by extract-tests.sh

use super::*;

    fn make_message_entry(content: &str, role: &str) -> SessionEntry {
        let message = match role {
            "user" => AgentMessage::User { content: content.to_string() },
            "assistant" => AgentMessage::Assistant {
                content: vec![ContentBlock::Text { text: content.to_string() }],
                usage: None,
            },
            "system" => AgentMessage::System { content: content.to_string() },
            "tool" => AgentMessage::Tool {
                tool_call_id: "call_1".to_string(),
                tool_name: "test".to_string(),
                tool_arguments: serde_json::json!({}),
                result: content.to_string(),
            },
            _ => panic!("unknown role: {role}"),
        };
        SessionEntry::new_message(None, message)
    }

    fn make_compaction_entry() -> SessionEntry {
        SessionEntry::new_compaction(
            None,
            "Previous summary".to_string(),
            "kept_1".to_string(),
            10000,
        )
    }

    #[test]
    fn find_cut_point_basic() {
        let entries = vec![
            SessionEntry::new_session(
                "session_1".to_string(),
                "2024-01-01T00:00:00Z".to_string(),
                "/cwd".to_string(),
                "model".to_string(),
                32768,
            ),
            make_message_entry("Hello", "user"),
            make_message_entry("Hi there", "assistant"),
            make_message_entry("How are you?", "user"),
            make_message_entry("I'm fine", "assistant"),
        ];

        let cut = CompactionSettings::find_cut_point(&entries, 1, 5, 10);
        assert!(cut.is_some());
        assert!(cut.unwrap() >= 1);
    }

    #[test]
    fn find_cut_point_stops_at_compaction_boundary() {
        let entries = vec![
            SessionEntry::new_session(
                "session_1".to_string(),
                "2024-01-01T00:00:00Z".to_string(),
                "/cwd".to_string(),
                "model".to_string(),
                32768,
            ),
            make_message_entry("Old message 1", "user"),
            make_message_entry("Old response 1", "assistant"),
            make_compaction_entry(),
            make_message_entry("New message 1", "user"),
            make_message_entry("New response 1", "assistant"),
        ];

        // Should stop at compaction boundary (index 3)
        let cut = CompactionSettings::find_cut_point(&entries, 4, 6, 100000);
        assert!(cut.is_none() || cut.unwrap() >= 4);
    }

    #[test]
    fn find_cut_point_skips_tool_results() {
        let entries = vec![
            SessionEntry::new_session(
                "session_1".to_string(),
                "2024-01-01T00:00:00Z".to_string(),
                "/cwd".to_string(),
                "model".to_string(),
                32768,
            ),
            make_message_entry("Run this", "user"),
            make_message_entry("", "assistant"),
            make_message_entry("tool output", "tool"),
            make_message_entry("Done", "assistant"),
        ];

        let cut = CompactionSettings::find_cut_point(&entries, 1, 5, 10);
        if let Some(cut_idx) = cut {
            assert_ne!(cut_idx, 3, "should not cut at tool result");
        }
    }

    #[test]
    fn extract_file_operations_reads_and_writes() {
        let read_args = serde_json::json!({"path": "src/main.rs"});
        let write_args = serde_json::json!({"path": "src/lib.rs"});

        let entries = vec![
            SessionEntry::new_session(
                "session_1".to_string(),
                "2024-01-01T00:00:00Z".to_string(),
                "/cwd".to_string(),
                "model".to_string(),
                32768,
            ),
            SessionEntry::new_message(
                None,
                AgentMessage::Assistant {
                    content: vec![
                        crate::session::ContentBlock::ToolCall { tool_call: ToolCall {
                            id: "call_1".to_string(),
                            name: "read".to_string(),
                            arguments: read_args,
                        }},
                        crate::session::ContentBlock::ToolCall { tool_call: ToolCall {
                            id: "call_2".to_string(),
                            name: "write".to_string(),
                            arguments: write_args,
                        }},
                    ],
                    usage: None,
                },
            ),
            make_message_entry("result", "user"),
        ];

        let (read_files, modified_files) = CompactionSettings::extract_file_operations(&entries, 3);
        assert_eq!(read_files, vec!["src/main.rs"]);
        assert_eq!(modified_files, vec!["src/lib.rs"]);
    }

    #[test]
    fn extract_file_operations_edit_goes_to_modified() {
        let edit_args = serde_json::json!({"path": "src/edit.rs", "oldText": "a", "newText": "b"});

        let entries = vec![
            SessionEntry::new_session(
                "session_1".to_string(),
                "2024-01-01T00:00:00Z".to_string(),
                "/cwd".to_string(),
                "model".to_string(),
                32768,
            ),
            SessionEntry::new_message(
                None,
                AgentMessage::Assistant {
                    content: vec![
                        crate::session::ContentBlock::ToolCall { tool_call: ToolCall {
                            id: "call_1".to_string(),
                            name: "edit".to_string(),
                            arguments: edit_args,
                        }},
                    ],
                    usage: None,
                },
            ),
        ];

        let (read_files, modified_files) = CompactionSettings::extract_file_operations(&entries, 2);
        assert!(read_files.is_empty());
        assert_eq!(modified_files, vec!["src/edit.rs"]);
    }

    #[test]
    fn summarize_prompt_includes_previous_summary() {
        let prompt = CompactionSettings::summarization_user_prompt(
            "[User] hello\n[Assistant] hi",
            Some("## Goal\nBuild a CLI app"),
            4096,
        );
        assert!(prompt.contains("<previous-summary>"));
        assert!(prompt.contains("Build a CLI app"));
        assert!(prompt.contains("<conversation>"));
        assert!(prompt.contains("[User] hello"));
    }

    #[test]
    fn summarize_prompt_without_previous_summary() {
        let prompt = CompactionSettings::summarization_user_prompt(
            "[User] hello",
            None,
            4096,
        );
        assert!(!prompt.contains("<previous-summary>"));
        assert!(prompt.contains("<conversation>"));
        assert!(prompt.contains("## Goal"));
    }

    #[test]
    fn find_cut_point_by_count_splits_half() {
        let entries = vec![
            SessionEntry::new_session(
                "session_1".to_string(),
                "2024-01-01T00:00:00Z".to_string(),
                "/cwd".to_string(),
                "model".to_string(),
                32768,
            ),
            make_message_entry("Message 1", "user"),
            make_message_entry("Response 1", "assistant"),
            make_message_entry("Message 2", "user"),
            make_message_entry("Response 2", "assistant"),
            make_message_entry("Message 3", "user"),
            make_message_entry("Response 3", "assistant"),
        ];

        // 6 messages (indices 1-6), should split at midpoint (index 4)
        let cut = CompactionSettings::find_cut_point_by_count(&entries, 1, 7);
        assert_eq!(cut, Some(4)); // Compact entries 1-3, keep entries 4-6
    }

    #[test]
    fn find_cut_point_by_count_too_few_entries() {
        let entries = vec![
            SessionEntry::new_session(
                "session_1".to_string(),
                "2024-01-01T00:00:00Z".to_string(),
                "/cwd".to_string(),
                "model".to_string(),
                32768,
            ),
            make_message_entry("Only message", "user"),
        ];

        // Only 1 message, can't meaningfully compact
        let cut = CompactionSettings::find_cut_point_by_count(&entries, 1, 2);
        assert_eq!(cut, None);
    }

    #[test]
    fn find_cut_point_by_count_excludes_tool_results() {
        let entries = vec![
            SessionEntry::new_session(
                "session_1".to_string(),
                "2024-01-01T00:00:00Z".to_string(),
                "/cwd".to_string(),
                "model".to_string(),
                32768,
            ),
            make_message_entry("Run this", "user"),
            make_message_entry("", "assistant"),
            make_message_entry("tool output", "tool"),
            make_message_entry("Done", "assistant"),
            make_message_entry("Next", "user"),
            make_message_entry("Final", "assistant"),
        ];

        // Valid cuts: 1(user), 2(assistant), 4(assistant), 5(user), 6(assistant)
        // Tool result at index 3 is excluded
        // Midpoint of 5 valid cuts = index 2, so cut at valid_cuts[2] = 4
        let cut = CompactionSettings::find_cut_point_by_count(&entries, 1, 7);
        assert_eq!(cut, Some(4));
    }

    #[test]
    fn find_cut_point_off_by_one_fixed() {
        // Test that when threshold is hit, we return i+1, not i
        // NOTE: The caller (compute_compaction/perform) enforces MIN_KEEP_MESSAGES
        // floor to prevent this from compacting everything in practice.
        let entries = vec![
            SessionEntry::new_session(
                "session_1".to_string(),
                "2024-01-01T00:00:00Z".to_string(),
                "/cwd".to_string(),
                "model".to_string(),
                32768,
            ),
            make_message_entry("A", "user"),         // index 1, 0 tokens (1/4=0)
            make_message_entry("BBBB", "assistant"), // index 2, 1 token
            make_message_entry("CCCCCCCC", "user"),  // index 3, 2 tokens
            make_message_entry("DDDDDDDD", "assistant"), // index 4, 2 tokens
        ];

        // keep_recent_tokens = 2
        // Walk: index 4 (2 tokens, accumulated=2 >= 2) → return min(4+1, 5) = 5
        // This means keep from index 5 onward (nothing), compact 1-4
        // But wait, 5 >= end_index (5), so this means keep nothing and compact everything.
        // Actually min(5, 5) = 5, which means "keep from index 5" = keep nothing.
        // The cut point is the FIRST entry to KEEP, so cut=5 means keep entries 5..5 = empty.
        let cut = CompactionSettings::find_cut_point(&entries, 1, 5, 2);
        assert_eq!(cut, Some(5)); // Compact everything (keep nothing from the range)

        // With a higher threshold, we should keep some entries
        // keep_recent_tokens = 3
        // Walk: index 4 (2 tokens, acc=2 < 3), index 3 (2 tokens, acc=4 >= 3) → return min(3+1, 5) = 4
        let cut = CompactionSettings::find_cut_point(&entries, 1, 5, 3);
        assert_eq!(cut, Some(4)); // Keep entry 4, compact entries 1-3
    }

    #[test]
    fn min_floor_blocks_over_aggressive_cut() {
        // When token-based cut keeps 0 messages, the floor guard should block.
        // This tests the caller-side guard, not the algorithm.
        let entries = vec![
            SessionEntry::new_session(
                "session_1".to_string(),
                "2024-01-01T00:00:00Z".to_string(),
                "/cwd".to_string(),
                "model".to_string(),
                32768,
            ),
            make_message_entry("A", "user"),
            make_message_entry("BBBB", "assistant"),
            make_message_entry("CCCCCCCC", "user"),
            make_message_entry("DDDDDDDD", "assistant"),
        ];

        // cut_index = 5 (keep nothing), boundary_end = 5
        // kept_message_count = 0 < MIN_KEEP_MESSAGES = 4
        let cut = CompactionSettings::find_cut_point(&entries, 1, 5, 2);
        assert_eq!(cut, Some(5));

        let kept_message_count = entries[5..5]
            .iter()
            .filter(|e| matches!(e, SessionEntry::Message { .. }))
            .count();
        assert_eq!(kept_message_count, 0);
        assert!(
            kept_message_count < CompactionSettings::MIN_KEEP_MESSAGES,
            "Floor would block this cut"
        );
    }

    #[test]
    fn min_floor_allows_sufficient_context() {
        // When cut keeps ≥4 messages, the floor guard allows it.
        let entries = vec![
            SessionEntry::new_session(
                "session_1".to_string(),
                "2024-01-01T00:00:00Z".to_string(),
                "/cwd".to_string(),
                "model".to_string(),
                32768,
            ),
            make_message_entry("Old 1", "user"),         // 1
            make_message_entry("Old 2", "assistant"),    // 2
            make_message_entry("Old 3", "user"),         // 3
            make_message_entry("Old 4", "assistant"),    // 4
            make_message_entry("Recent 1", "user"),      // 5
            make_message_entry("Recent 2", "assistant"), // 6
            make_message_entry("Recent 3", "user"),      // 7
            make_message_entry("Recent 4", "assistant"), // 8
        ];

        // With a moderate threshold, cut should land somewhere in the middle.
        let cut = CompactionSettings::find_cut_point(&entries, 1, 9, 10);
        assert!(cut.is_some());
        let cut = cut.unwrap();

        let kept_message_count = entries[cut..9]
            .iter()
            .filter(|e| matches!(e, SessionEntry::Message { .. }))
            .count();
        assert!(
            kept_message_count >= CompactionSettings::MIN_KEEP_MESSAGES,
            "Floor requires {} messages, cut keeps {}",
            CompactionSettings::MIN_KEEP_MESSAGES,
            kept_message_count
        );
    }

    #[test]
    fn min_floor_boundary_exact() {
        // Exactly 4 messages kept → allowed
        // Exactly 3 messages kept → blocked
        let entries: &[SessionEntry] = &[
            SessionEntry::new_session(
                "session_1".to_string(),
                "2024-01-01T00:00:00Z".to_string(),
                "/cwd".to_string(),
                "model".to_string(),
                32768,
            ),
            make_message_entry("Compact me", "user"),    // 1
            make_message_entry("Compact me too", "assistant"), // 2
            make_message_entry("Keep 1", "user"),        // 3
            make_message_entry("Keep 2", "assistant"),   // 4
            make_message_entry("Keep 3", "user"),        // 5
            make_message_entry("Keep 4", "assistant"),   // 6
        ];

        // cut_index = 3 → keeps entries 3..7 = 4 messages → allowed
        let kept_at_3 = entries[3..7]
            .iter()
            .filter(|e| matches!(e, SessionEntry::Message { .. }))
            .count();
        assert_eq!(kept_at_3, 4);
        assert!(kept_at_3 >= CompactionSettings::MIN_KEEP_MESSAGES);

        // cut_index = 4 → keeps entries 4..7 = 3 messages → blocked
        let kept_at_4 = entries[4..7]
            .iter()
            .filter(|e| matches!(e, SessionEntry::Message { .. }))
            .count();
        assert_eq!(kept_at_4, 3);
        assert!(kept_at_4 < CompactionSettings::MIN_KEEP_MESSAGES);
    }
