// Extracted tests from src/session/entry.rs
// Auto-generated by extract-tests.sh

use super::{SessionEntry, AgentMessage, ToolCall, Usage, RequestTokenUsage, TokenRateEntry};

    // ---------------------------------------------------------------------------
    // SessionEntry serialization
    // ---------------------------------------------------------------------------

    #[test]
    fn session_entry_session_roundtrip() {
        let entry = SessionEntry::new_session(
            "abc-123".to_string(),
            "2025-01-01T00:00:00Z".to_string(),
            "/home/user".to_string(),
            "llama3.2".to_string(),
            32768,
        );
        let json = serde_json::to_string(&entry).unwrap();
        let decoded: SessionEntry = serde_json::from_str(&json).unwrap();
        assert_eq!(entry.id(), decoded.id());
    }

    #[test]
    fn session_entry_message_roundtrip() {
        let msg = AgentMessage::user("hello".to_string());
        let entry = SessionEntry::new_message(None, msg);
        let json = serde_json::to_string(&entry).unwrap();
        assert!(json.contains("\"type\":\"message\""));
        let decoded: SessionEntry = serde_json::from_str(&json).unwrap();
        assert_eq!(entry.id(), decoded.id());
    }

    #[test]
    fn session_entry_compaction_roundtrip() {
        let entry = SessionEntry::new_compaction(
            Some("parent-1".to_string()),
            "Summary of conversation".to_string(),
            "first-entry".to_string(),
            5000,
        );
        let json = serde_json::to_string(&entry).unwrap();
        assert!(json.contains("\"type\":\"compaction\""));
        let decoded: SessionEntry = serde_json::from_str(&json).unwrap();
        assert_eq!(entry.id(), decoded.id());
        assert_eq!(entry.parent_id(), decoded.parent_id());
    }

    #[test]
    fn session_entry_model_change_roundtrip() {
        let entry = SessionEntry::new_model_change(
            Some("parent-1".to_string()),
            "gpt-4".to_string(),
            8192,
        );
        let json = serde_json::to_string(&entry).unwrap();
        let decoded: SessionEntry = serde_json::from_str(&json).unwrap();
        assert_eq!(entry.id(), decoded.id());
    }

    #[test]
    fn session_entry_custom_roundtrip() {
        let data = serde_json::json!({"tokens": 100, "seconds": 5.0});
        let entry = SessionEntry::new_custom("token_rate".to_string(), data);
        let json = serde_json::to_string(&entry).unwrap();
        let decoded: SessionEntry = serde_json::from_str(&json).unwrap();
        // Custom entries have empty id
        assert_eq!(entry.id(), String::new());
        assert_eq!(decoded.id(), String::new());
    }

    // ---------------------------------------------------------------------------
    // AgentMessage serialization
    // ---------------------------------------------------------------------------

    #[test]
    fn agent_message_assistant_with_tool_calls() {
        let msg = AgentMessage::assistant(
            "result".to_string(),
            String::new(),
            vec![ToolCall {
                id: "call_1".to_string(),
                name: "search".to_string(),
                arguments: serde_json::json!({"query": "rust"}),
            }],
            Some(Usage { prompt_tokens: 100, completion_tokens: 50, total_tokens: 150 }),
        );
        let json = serde_json::to_string(&msg).unwrap();
        assert!(json.contains("\"role\":\"assistant\""));
        assert!(json.contains("\"search\""));
        let decoded: AgentMessage = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.content(), "result");
    }

    #[test]
    fn agent_message_assistant_without_usage() {
        let msg = AgentMessage::assistant("hi".to_string(), String::new(), Vec::new(), None);
        let json = serde_json::to_string(&msg).unwrap();
        // usage should be omitted (skip_serializing_if)
        assert!(!json.contains("usage"));
        let decoded: AgentMessage = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.content(), "hi");
    }

    #[test]
    fn agent_message_tool_roundtrip() {
        let args = serde_json::json!({"path": "src/main.rs"});
        let msg = AgentMessage::tool("call_1".to_string(), "read".to_string(), args, "file contents".to_string());
        let json = serde_json::to_string(&msg).unwrap();
        assert!(json.contains("\"role\":\"tool\""));
        assert!(json.contains("\"tool_name\":\"read\""));
        let decoded: AgentMessage = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.content(), "file contents");
    }

    // ---------------------------------------------------------------------------
    // AgentMessage content()
    // ---------------------------------------------------------------------------

    #[test]
    fn agent_message_content_all_variants() {
        assert_eq!(AgentMessage::system("sys".to_string()).content(), "sys");
        assert_eq!(AgentMessage::user("user".to_string()).content(), "user");
        assert_eq!(AgentMessage::assistant("assistant".to_string(), String::new(), Vec::new(), None).content(), "assistant");
        assert_eq!(AgentMessage::tool("id".to_string(), "read".to_string(), serde_json::json!({}), "tool result".to_string()).content(), "tool result");
    }

    // ---------------------------------------------------------------------------
    // RequestTokenUsage
    // ---------------------------------------------------------------------------

    #[test]
    fn request_token_usage_total() {
        let usage = RequestTokenUsage { input_tokens: 100, output_tokens: 50, estimated: false };
        assert_eq!(usage.total(), 150);
    }

    #[test]
    fn request_token_usage_delta() {
        let prev = RequestTokenUsage { input_tokens: 100, output_tokens: 50, estimated: false };
        let curr = RequestTokenUsage { input_tokens: 200, output_tokens: 120, estimated: false };
        let delta = curr.delta(&prev);
        assert_eq!(delta.input_tokens, 100);
        assert_eq!(delta.output_tokens, 70);
    }

    #[test]
    fn request_token_usage_delta_saturates() {
        let prev = RequestTokenUsage { input_tokens: 200, output_tokens: 100, estimated: false };
        let curr = RequestTokenUsage { input_tokens: 100, output_tokens: 50, estimated: false };
        let delta = curr.delta(&prev);
        // Should saturate at 0, not underflow
        assert_eq!(delta.input_tokens, 0);
        assert_eq!(delta.output_tokens, 0);
    }

    #[test]
    fn request_token_usage_default() {
        let usage = RequestTokenUsage::default();
        assert_eq!(usage.input_tokens, 0);
        assert_eq!(usage.output_tokens, 0);
        assert_eq!(usage.total(), 0);
    }

    // ---------------------------------------------------------------------------
    // TokenRateEntry
    // ---------------------------------------------------------------------------

    #[test]
    fn token_rate_entry() {
        let entry = TokenRateEntry::new(100, 5.0);
        assert_eq!(entry.tokens, 100);
        assert!((entry.seconds - 5.0).abs() < f64::EPSILON);
    }

    #[test]
    fn token_rate_entry_serialization() {
        let entry = TokenRateEntry::new(100, 5.0);
        let json = serde_json::to_string(&entry).unwrap();
        assert!(json.contains("\"tokens\":100"));
        let decoded: TokenRateEntry = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.tokens, 100);
    }

    // ---------------------------------------------------------------------------
    // SessionEntry id() and parent_id()
    // ---------------------------------------------------------------------------

    #[test]
    fn session_entry_id_returns_correct_values() {
        let session = SessionEntry::new_session(
            "sess-1".to_string(), "ts".to_string(), "/".to_string(), "model".to_string(), 4096,
        );
        assert_eq!(session.id(), "sess-1");

        let msg = SessionEntry::new_message(Some("sess-1".to_string()), AgentMessage::user("hi".to_string()));
        assert!(!msg.id().is_empty());
        assert_eq!(msg.parent_id(), Some("sess-1".to_string()));
    }

    #[test]
    fn session_entry_session_has_no_parent() {
        let session = SessionEntry::new_session(
            "sess-1".to_string(), "ts".to_string(), "/".to_string(), "model".to_string(), 4096,
        );
        assert_eq!(session.parent_id(), None);
    }
