// Extracted tests from src/session/manager.rs
// Auto-generated by extract-tests.sh

use super::{SessionStore, SessionEntry, AgentMessage, TokenRateEntry};
    use crate::session::Usage;
    use std::fs;
    use std::path::PathBuf;

    fn temp_dir() -> PathBuf {
        let dir = std::env::temp_dir().join(format!("respondami_test_{}", uuid::Uuid::new_v4()));
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    // ---------------------------------------------------------------------------
    // create_session
    // ---------------------------------------------------------------------------

    #[test]
    fn create_session_returns_uuid() {
        let dir = temp_dir();
        let mut manager = SessionStore::new(&dir);
        let id = manager.create_session("llama3.2".to_string(), 32768, "/home/user".to_string());
        assert!(!id.is_empty());
        assert!(manager.has_active_session());
        assert_eq!(manager.session_id(), Some(id.as_str()));
    }

    #[test]
    fn create_session_creates_file() {
        let dir = temp_dir();
        let mut manager = SessionStore::new(&dir);
        let id = manager.create_session("llama3.2".to_string(), 32768, "/home/user".to_string());
        let path = manager.sessions_dir().join(format!("{id}.jsonl"));
        assert!(path.exists());
    }

    #[test]
    fn create_session_sets_model() {
        let dir = temp_dir();
        let mut manager = SessionStore::new(&dir);
        manager.create_session("gpt-4".to_string(), 8192, "/".to_string());
        assert_eq!(manager.model_name(), Some("gpt-4".to_string()));
    }

    // ---------------------------------------------------------------------------
    // append_message
    // ---------------------------------------------------------------------------

    #[test]
    fn append_message_adds_entry() {
        let dir = temp_dir();
        let mut manager = SessionStore::new(&dir);
        manager.create_session("llama3.2".to_string(), 32768, "/".to_string());
        let id = manager.append_message(None, AgentMessage::user("hello".to_string())).unwrap();
        assert!(!id.is_empty());
        assert_eq!(manager.entries().len(), 2); // header + message
    }

    #[test]
    fn append_message_writes_to_disk() {
        let dir = temp_dir();
        let mut manager = SessionStore::new(&dir);
        let session_id = manager.create_session("llama3.2".to_string(), 32768, "/".to_string());
        manager.append_message(None, AgentMessage::user("hello".to_string())).unwrap();

        let path = manager.sessions_dir().join(format!("{session_id}.jsonl"));
        let content = fs::read_to_string(path).unwrap();
        let lines: Vec<&str> = content.lines().collect();
        assert!(lines.len() >= 2); // header + message
    }

    // ---------------------------------------------------------------------------
    // load_session
    // ---------------------------------------------------------------------------

    #[test]
    fn load_session_reads_entries() {
        let dir = temp_dir();
        // Create a session
        let mut manager1 = SessionStore::new(&dir);
        let id = manager1.create_session("llama3.2".to_string(), 32768, "/".to_string());
        manager1.append_message(None, AgentMessage::user("hello".to_string())).unwrap();
        manager1.append_message(None, AgentMessage::assistant("hi".to_string(), String::new(), Vec::new(), None)).unwrap();

        // Load it in a new manager
        let mut manager2 = SessionStore::new(&dir);
        let path = manager1.sessions_dir().join(format!("{id}.jsonl"));
        let entries = manager2.load_session(&path).unwrap();
        assert_eq!(entries.len(), 3); // header + 2 messages
        assert_eq!(manager2.session_id(), Some(id.as_str()));
    }

    #[test]
    fn load_session_skips_empty_lines() {
        let dir = temp_dir();
        let mut manager = SessionStore::new(&dir);
        let id = manager.create_session("llama3.2".to_string(), 32768, "/".to_string());

        // Add empty lines to the file
        let path = manager.sessions_dir().join(format!("{id}.jsonl"));
        let mut content = fs::read_to_string(&path).unwrap();
        content.push_str("\n\n");
        fs::write(&path, content).unwrap();

        // Load should handle empty lines gracefully
        let entries = manager.load_session(&path).unwrap();
        assert_eq!(entries.len(), 1); // just the header
    }

    // ---------------------------------------------------------------------------
    // build_context
    // ---------------------------------------------------------------------------

    #[test]
    fn build_context_skips_header() {
        let dir = temp_dir();
        let mut manager = SessionStore::new(&dir);
        manager.create_session("llama3.2".to_string(), 32768, "/".to_string());
        manager.append_message(None, AgentMessage::user("hello".to_string())).unwrap();
        manager.append_message(None, AgentMessage::assistant("hi".to_string(), String::new(), Vec::new(), None)).unwrap();

        let context = manager.build_context();
        assert_eq!(context.len(), 2); // user + assistant (no header)
    }

    #[test]
    fn build_context_injects_compaction_summary() {
        let dir = temp_dir();
        let mut manager = SessionStore::new(&dir);
        manager.create_session("llama3.2".to_string(), 32768, "/".to_string());

        // Add a compaction entry
        let compaction = SessionEntry::new_compaction(
            None,
            "Summary of earlier conversation".to_string(),
            "next-entry-id".to_string(),
            5000,
        );
        manager.append_entry(compaction).unwrap();

        // Add a message with the skip_until ID
        let next_msg = SessionEntry::new_message(None, AgentMessage::user("new topic".to_string()));
        // Override the ID to match first_kept_entry_id
        // (can't easily do this, so just check that summary is injected)
        manager.append_entry(next_msg).unwrap();

        let context = manager.build_context();
        // Should have the summary system message
        assert!(context.iter().any(|m| m.content().contains("Summary of earlier conversation")));
    }

    // ---------------------------------------------------------------------------
    // last_entry_id
    // ---------------------------------------------------------------------------

    #[test]
    fn last_entry_id_returns_last() {
        let dir = temp_dir();
        let mut manager = SessionStore::new(&dir);
        manager.create_session("llama3.2".to_string(), 32768, "/".to_string());
        assert!(manager.last_entry_id().is_some());

        manager.append_message(None, AgentMessage::user("hello".to_string())).unwrap();
        let last_id = manager.last_entry_id().unwrap();
        assert!(!last_id.is_empty());
    }

    #[test]
    fn last_entry_id_empty_before_session() {
        let dir = temp_dir();
        let manager = SessionStore::new(&dir);
        assert!(manager.last_entry_id().is_none());
    }

    // ---------------------------------------------------------------------------
    // total_usage
    // ---------------------------------------------------------------------------

    #[test]
    fn total_usage_sums_assistant_usage_separately() {
        let dir = temp_dir();
        let mut manager = SessionStore::new(&dir);
        manager.create_session("llama3.2".to_string(), 32768, "/".to_string());

        // Add assistant message with usage
        let msg = AgentMessage::assistant(
            "response".to_string(),
            String::new(),
            Vec::new(),
            Some(Usage { prompt_tokens: 100, completion_tokens: 50, total_tokens: 150 }),
        );
        manager.append_message(None, msg).unwrap();

        let (input, output) = manager.total_usage();
        assert_eq!(input, 100);
        assert_eq!(output, 50);
    }

    #[test]
    fn total_usage_ignores_non_assistant() {
        let dir = temp_dir();
        let mut manager = SessionStore::new(&dir);
        manager.create_session("llama3.2".to_string(), 32768, "/".to_string());
        manager.append_message(None, AgentMessage::user("hello".to_string())).unwrap();

        let (input, output) = manager.total_usage();
        assert_eq!(input, 0);
        assert_eq!(output, 0);
    }

    // ---------------------------------------------------------------------------
    // total_token_rate
    // ---------------------------------------------------------------------------

    #[test]
    fn total_token_rate_sums_entries() {
        let dir = temp_dir();
        let mut manager = SessionStore::new(&dir);
        manager.create_session("llama3.2".to_string(), 32768, "/".to_string());

        manager.save_token_rate(TokenRateEntry::new(100, 5.0));
        manager.save_token_rate(TokenRateEntry::new(200, 10.0));

        let (tokens, seconds) = manager.total_token_rate();
        assert_eq!(tokens, 300);
        assert!((seconds - 15.0).abs() < f64::EPSILON);
    }

    #[test]
    fn total_token_rate_empty() {
        let dir = temp_dir();
        let mut manager = SessionStore::new(&dir);
        manager.create_session("llama3.2".to_string(), 32768, "/".to_string());

        let (tokens, seconds) = manager.total_token_rate();
        assert_eq!(tokens, 0);
        assert_eq!(seconds, 0.0);
    }

    // ---------------------------------------------------------------------------
    // estimate_token_count
    // ---------------------------------------------------------------------------

    #[test]
    fn estimate_token_count_positive() {
        let dir = temp_dir();
        let mut manager = SessionStore::new(&dir);
        manager.create_session("llama3.2".to_string(), 32768, "/".to_string());
        manager.append_message(None, AgentMessage::user("hello world this is a test".to_string())).unwrap();

        let count = manager.estimate_token_count();
        assert!(count > 0);
    }

    // ---------------------------------------------------------------------------
    // has_active_session / session_id
    // ---------------------------------------------------------------------------

    #[test]
    fn has_active_session_false_initially() {
        let dir = temp_dir();
        let manager = SessionStore::new(&dir);
        assert!(!manager.has_active_session());
        assert!(manager.session_id().is_none());
    }
