// Extracted tests from src/key_handler/layers/input.rs
// Auto-generated by extract-tests.sh

use super::input::{key_allows_newline, InputLayer, InputConfig};
use crossterm::event::KeyModifiers;

    #[test]
    fn key_allows_newline_shift() {
        assert!(key_allows_newline(&KeyModifiers::SHIFT));
    }

    #[test]
    fn key_allows_newline_alt() {
        assert!(key_allows_newline(&KeyModifiers::ALT));
    }

    #[test]
    fn key_allows_newline_none() {
        assert!(!key_allows_newline(&KeyModifiers::NONE));
    }

    #[test]
    fn key_allows_newline_control() {
        assert!(!key_allows_newline(&KeyModifiers::CONTROL));
    }

    #[test]
    fn input_config_default() {
        let config = InputConfig::default();
        assert!(!config.allow_newlines);
        assert!(!config.enable_at_trigger);
    }

    #[test]
    fn input_layer_builder() {
        let layer = InputLayer::new(InputConfig {
            allow_newlines: true,
            ..Default::default()
        })
        .with_at_trigger(Box::new(|_| {}));

        assert!(layer.config.allow_newlines);
        assert!(layer.at_trigger.is_some());
    }
