// Extracted tests from src/key_handler/layers/modal.rs
// Auto-generated by extract-tests.sh

use super::modal::ModalLayer;
use crate::tui::AppState;
use crossterm::event::{KeyCode, KeyEvent, KeyEventKind, KeyEventState, KeyModifiers};

    fn make_key(code: KeyCode, modifiers: KeyModifiers) -> KeyEvent {
        KeyEvent {
            code,
            modifiers,
            kind: KeyEventKind::Press,
            state: KeyEventState::NONE,
        }
    }

    #[test]
    fn ctrl_d_always_quit() {
        // Ctrl+D should always return true (quit) regardless of modal state
        let key = make_key(KeyCode::Char('d'), KeyModifiers::CONTROL);
        assert_eq!(key.code, KeyCode::Char('d'));
        assert!(key.modifiers.contains(KeyModifiers::CONTROL));
    }

    #[test]
    fn page_up_down_blocked_in_modal() {
        // When modal is open, PgUp/PgDown should not scroll
        let _layer = ModalLayer::new();
        // We can't test with a full App, but we can verify the modal check logic
        let modal_states = vec![
            AppState::SessionSelect,
            AppState::InitPopup,
            AppState::CommandPalette,
            AppState::HelpPopup,
        ];
        for state in modal_states {
            assert!(
                matches!(
                    state,
                    AppState::SessionSelect
                        | AppState::InitPopup
                        | AppState::CommandPalette
                        | AppState::HelpPopup
                ),
                "{state:?} should be a modal state"
            );
        }
    }

    #[test]
    fn f1_opens_help_popup() {
        let key = make_key(KeyCode::F(1), KeyModifiers::NONE);
        assert_eq!(key.code, KeyCode::F(1));
        assert!(!key.modifiers.contains(KeyModifiers::CONTROL));
    }

    #[test]
    fn esc_closes_help_popup() {
        let key = make_key(KeyCode::Esc, KeyModifiers::NONE);
        assert_eq!(key.code, KeyCode::Esc);
    }

    #[test]
    fn ctrl_o_toggles_thinking_display() {
        let key = make_key(KeyCode::Char('o'), KeyModifiers::CONTROL);
        assert_eq!(key.code, KeyCode::Char('o'));
        assert!(key.modifiers.contains(KeyModifiers::CONTROL));
    }

    #[test]
    fn ctrl_t_toggles_tool_output() {
        let key = make_key(KeyCode::Char('t'), KeyModifiers::CONTROL);
        assert_eq!(key.code, KeyCode::Char('t'));
        assert!(key.modifiers.contains(KeyModifiers::CONTROL));
    }
