// Extracted tests from src/key_handler/layers/navigation.rs
// Auto-generated by extract-tests.sh

use super::navigation::NavigationLayer;
use crate::tui::app::App;
use std::cell::Cell;
use std::rc::Rc;
use crossterm::event::{KeyCode, KeyEventKind, KeyEventState, KeyModifiers};

    fn make_key(code: KeyCode, modifiers: KeyModifiers) -> crossterm::event::KeyEvent {
        crossterm::event::KeyEvent {
            code,
            modifiers,
            kind: KeyEventKind::Press,
            state: KeyEventState::NONE,
        }
    }

    fn make_app() -> App {
        App::new(crate::config::Config::default(), std::path::PathBuf::from("."))
    }

    #[test]
    fn navigate_up_from_middle() {
        let selected = Rc::new(Cell::new(3usize));
        let selected_getter = {
            let s = Rc::clone(&selected);
            Box::new(move |_: &App| s.get())
        };
        let selected_setter = {
            let s = Rc::clone(&selected);
            Box::new(move |_: &mut App, idx| s.set(idx))
        };
        let item_count = Box::new(|_: &App| 5usize);

        let mut nav = NavigationLayer::new(item_count, selected_getter, selected_setter);
        let key = make_key(KeyCode::Up, KeyModifiers::NONE);
        let mut app = make_app();
        nav.handle(&mut app, &key).unwrap();
        assert_eq!(selected.get(), 2);
    }

    #[test]
    fn navigate_up_from_zero_cycles_to_end() {
        let selected = Rc::new(Cell::new(0usize));
        let selected_getter = {
            let s = Rc::clone(&selected);
            Box::new(move |_: &App| s.get())
        };
        let selected_setter = {
            let s = Rc::clone(&selected);
            Box::new(move |_: &mut App, idx| s.set(idx))
        };
        let item_count = Box::new(|_: &App| 5usize);

        let mut nav = NavigationLayer::new(item_count, selected_getter, selected_setter);
        let key = make_key(KeyCode::Up, KeyModifiers::NONE);
        let mut app = make_app();
        nav.handle(&mut app, &key).unwrap();
        assert_eq!(selected.get(), 4);
    }

    #[test]
    fn navigate_down_from_middle() {
        let selected = Rc::new(Cell::new(2usize));
        let selected_getter = {
            let s = Rc::clone(&selected);
            Box::new(move |_: &App| s.get())
        };
        let selected_setter = {
            let s = Rc::clone(&selected);
            Box::new(move |_: &mut App, idx| s.set(idx))
        };
        let item_count = Box::new(|_: &App| 5usize);

        let mut nav = NavigationLayer::new(item_count, selected_getter, selected_setter);
        let key = make_key(KeyCode::Down, KeyModifiers::NONE);
        let mut app = make_app();
        nav.handle(&mut app, &key).unwrap();
        assert_eq!(selected.get(), 3);
    }

    #[test]
    fn navigate_down_at_end_wraps_to_zero() {
        let selected = Rc::new(Cell::new(4usize));
        let selected_getter = {
            let s = Rc::clone(&selected);
            Box::new(move |_: &App| s.get())
        };
        let selected_setter = {
            let s = Rc::clone(&selected);
            Box::new(move |_: &mut App, idx| s.set(idx))
        };
        let item_count = Box::new(|_: &App| 5usize);

        let mut nav = NavigationLayer::new(item_count, selected_getter, selected_setter);
        let key = make_key(KeyCode::Down, KeyModifiers::NONE);
        let mut app = make_app();
        nav.handle(&mut app, &key).unwrap();
        assert_eq!(selected.get(), 0);
    }

    #[test]
    fn navigate_up_empty_list_noop() {
        let selected = Rc::new(Cell::new(0usize));
        let selected_getter = {
            let s = Rc::clone(&selected);
            Box::new(move |_: &App| s.get())
        };
        let selected_setter = {
            let s = Rc::clone(&selected);
            Box::new(move |_: &mut App, idx| s.set(idx))
        };
        let item_count = Box::new(|_: &App| 0usize);

        let mut nav = NavigationLayer::new(item_count, selected_getter, selected_setter);
        let key = make_key(KeyCode::Up, KeyModifiers::NONE);
        let mut app = make_app();
        nav.handle(&mut app, &key).unwrap();
        assert_eq!(selected.get(), 0);
    }
