// Extracted tests from src/key_handler/layers/transitions.rs
// Auto-generated by extract-tests.sh

use super::transitions::{StateTransitionLayer, TransitionAction};
use crate::tui::app::App;
use crossterm::event::{KeyCode, KeyEvent, KeyEventKind, KeyEventState, KeyModifiers};

    fn make_key(code: KeyCode, modifiers: KeyModifiers) -> KeyEvent {
        KeyEvent {
            code,
            modifiers,
            kind: KeyEventKind::Press,
            state: KeyEventState::NONE,
        }
    }

    fn make_app() -> App {
        App::new(crate::config::Config::default(), std::path::PathBuf::from("."))
    }

    #[test]
    fn enter_callback_returns_action() {
        let mut layer = StateTransitionLayer::new().with_enter(Box::new(|_| TransitionAction::Send));
        let key = make_key(KeyCode::Enter, KeyModifiers::NONE);
        let mut app = make_app();
        let result = layer.handle(&mut app, &key);
        assert_eq!(result, Some(TransitionAction::Send));
    }

    #[test]
    fn shift_enter_not_enter() {
        let mut layer = StateTransitionLayer::new().with_enter(Box::new(|_| TransitionAction::Send));
        let key = make_key(KeyCode::Enter, KeyModifiers::SHIFT);
        let mut app = make_app();
        let result = layer.handle(&mut app, &key);
        assert_eq!(result, None); // shift enter is handled by shift_enter callback
    }

    #[test]
    fn ctrl_c_key_identified() {
        let mut layer = StateTransitionLayer::new().with_ctrl_c(Box::new(|_| {}));
        let key = make_key(KeyCode::Char('c'), KeyModifiers::CONTROL);
        let mut app = make_app();
        let result = layer.handle(&mut app, &key);
        assert_eq!(result, Some(TransitionAction::None));
    }

    #[test]
    fn ctrl_g_key_identified() {
        let mut layer = StateTransitionLayer::new().with_ctrl_g(Box::new(|_| {}));
        let key = make_key(KeyCode::Char('g'), KeyModifiers::CONTROL);
        let mut app = make_app();
        let result = layer.handle(&mut app, &key);
        assert_eq!(result, Some(TransitionAction::None));
    }

    #[test]
    fn esc_key_identified() {
        let mut layer = StateTransitionLayer::new().with_esc(Box::new(|_| {}));
        let key = make_key(KeyCode::Esc, KeyModifiers::NONE);
        let mut app = make_app();
        let result = layer.handle(&mut app, &key);
        assert_eq!(result, Some(TransitionAction::None));
    }
