// Extracted tests from src/tui/messages/tool_call/mod.rs
// Auto-generated by extract-tests.sh

use super::{EditToolCall, BashToolCall, WriteToolCall, ToolCallRender, ToolCallMessage, ToolCallVariant, BashToolCall as BashTC, MAX_CONTENT_LINES};
    use ratatui_md::HeightAware;
    use crate::tui::theme::Theme;

    // ---------------------------------------------------------------------------
    // EditToolCall::from_args
    // ---------------------------------------------------------------------------

    #[test]
    fn edit_from_args_success() {
        let args = serde_json::json!({
            "path": "src/main.rs",
            "edits": [
                {"oldText": "fn old()", "newText": "fn new()"},
                {"oldText": "x = 1", "newText": "x = 2"}
            ]
        });
        let edit = EditToolCall::from_args("ok", false, Some(&args), false);
        assert_eq!(edit.path, "src/main.rs");
        assert_eq!(edit.edits.len(), 2);
        assert!(!edit.has_error);
        assert_eq!(edit.edits[0].old_text, "fn old()");
        assert_eq!(edit.edits[0].new_text, "fn new()");
    }

    #[test]
    fn edit_from_args_error() {
        let args = serde_json::json!({
            "path": "src/main.rs"
        });
        let edit = EditToolCall::from_args("file not found", true, Some(&args), false);
        assert_eq!(edit.path, "src/main.rs");
        assert!(edit.has_error);
        assert!(edit.edits.is_empty());
    }

    #[test]
    fn edit_from_args_no_args() {
        let edit = EditToolCall::from_args("", false, None, false);
        assert_eq!(edit.path, "unknown");
        assert!(edit.edits.is_empty());
    }

    #[test]
    fn edit_from_args_empty_edits() {
        let args = serde_json::json!({
            "path": "src/main.rs",
            "edits": []
        });
        let edit = EditToolCall::from_args("", false, Some(&args), false);
        assert_eq!(edit.edits.len(), 0);
    }

    #[test]
    fn edit_from_args_partial_edit_fields() {
        let args = serde_json::json!({
            "path": "src/main.rs",
            "edits": [
                {"oldText": "a", "newText": "b"},
                {"oldText": "c"}
            ]
        });
        let edit = EditToolCall::from_args("", false, Some(&args), false);
        assert_eq!(edit.edits.len(), 1);
    }

    // ---------------------------------------------------------------------------
    // BashToolCall::from_args
    // ---------------------------------------------------------------------------

    #[test]
    fn bash_from_args_success() {
        let args = serde_json::json!({
            "command": "ls -la"
        });
        let bash = BashToolCall::from_args("file1\nfile2", false, Some(&args), None, false);
        assert_eq!(bash.command, "ls -la");
        assert_eq!(bash.output, "file1\nfile2");
        assert!(!bash.has_error);
    }

    #[test]
    fn bash_from_args_error() {
        let args = serde_json::json!({
            "command": "cat missing.txt"
        });
        let bash = BashToolCall::from_args("No such file", true, Some(&args), None, false);
        assert!(bash.has_error);
    }

    #[test]
    fn bash_from_args_no_args() {
        let bash = BashToolCall::from_args("output", false, None, None, false);
        assert_eq!(bash.command, "unknown");
    }

    // ---------------------------------------------------------------------------
    // ToolCallRender trait
    // ---------------------------------------------------------------------------

    #[test]
    fn render_content_lines_empty() {
        let bash = BashToolCall::from_args("", false, None, None, false);
        let lines = bash.content_lines();
        assert!(lines.is_empty());
    }

    #[test]
    fn render_content_lines_under_limit() {
        let bash = BashToolCall::from_args("line 0\nline 1\nline 2\nline 3\nline 4", false, None, None, false);
        let lines = bash.content_lines();
        assert_eq!(lines.len(), 5);
    }

    #[test]
    fn render_content_lines_at_limit() {
        let output: String = (0..10).map(|i| format!("l{i}")).collect::<Vec<_>>().join("\n");
        let bash = BashToolCall::from_args(&output, false, None, None, false);
        let lines = bash.content_lines();
        assert_eq!(lines.len(), 10);
    }

    #[test]
    fn render_content_lines_over_limit() {
        let output: String = (0..15).map(|i| format!("line {i}")).collect::<Vec<_>>().join("\n");
        let bash = BashToolCall::from_args(&output, false, None, None, false);
        let lines = bash.content_lines();
        assert_eq!(lines.len(), 15);
    }

    // ---------------------------------------------------------------------------
    // HeightAware for ToolCallMessage — height must match render_into truncation
    // ---------------------------------------------------------------------------

    fn dummy_theme() -> Theme {
        Theme::gh_dark()
    }

    #[test]
    fn tool_call_height_empty_content() {
        // Empty non-error output: shows "(no output)" = 1 content line
        let bash = BashTC::from_args("", false, None, None, false);
        let msg = ToolCallMessage { variant: ToolCallVariant::Bash(bash) };
        // FilledHeaderBar: 2 (header+border) + 1 ("(no output)") = 3
        assert_eq!(msg.height(80, &dummy_theme()), 3);
    }

    #[test]
    fn tool_call_height_under_limit() {
        // 5 lines of short content → 5 content lines
        let output: String = (0..5).map(|i| format!("line {i}")).collect::<Vec<_>>().join("\n");
        let bash = BashTC::from_args(&output, false, None, None, false);
        let msg = ToolCallMessage { variant: ToolCallVariant::Bash(bash) };
        // 2 (header+border) + 5 content = 7
        assert_eq!(msg.height(80, &dummy_theme()), 7);
    }

    #[test]
    fn tool_call_height_at_limit() {
        // Exactly MAX_CONTENT_LINES (10) → no truncation summary
        let output: String = (0..MAX_CONTENT_LINES).map(|i| format!("line {i}")).collect::<Vec<_>>().join("\n");
        let bash = BashTC::from_args(&output, false, None, None, false);
        let msg = ToolCallMessage { variant: ToolCallVariant::Bash(bash) };
        // 2 + 10 = 12
        assert_eq!(msg.height(80, &dummy_theme()), 12);
    }

    #[test]
    fn tool_call_height_over_limit_collapsed() {
        // 100 lines, collapsed → FilledHeaderBar::collapsed(true) = header(2) + 1 collapsed indicator = 3
        let output: String = (0..100).map(|i| format!("line {i}")).collect::<Vec<_>>().join("\n");
        let bash = BashTC::from_args(&output, false, None, None, false);
        let msg = ToolCallMessage { variant: ToolCallVariant::Bash(bash) };
        assert_eq!(msg.height(80, &dummy_theme()), 3);
    }

    #[test]
    fn tool_call_height_error_shows_all_lines() {
        // Error output: no truncation — all lines counted
        let output: String = (0..50).map(|i| format!("error line {i}")).collect::<Vec<_>>().join("\n");
        let bash = BashTC::from_args(&output, true, None, None, false);
        let msg = ToolCallMessage { variant: ToolCallVariant::Bash(bash) };
        // 2 + 50 = 52
        assert_eq!(msg.height(80, &dummy_theme()), 52);
    }

    #[test]
    fn tool_call_height_wraps_long_lines() {
        // One very long line that wraps across 3 rows at width=40
        let long_line = "x".repeat(100);
        let bash = BashTC::from_args(&long_line, false, None, None, false);
        let msg = ToolCallMessage { variant: ToolCallVariant::Bash(bash) };
        // Effective width = 40 - 2 = 38. 100 / 38 = 3 (ceil)
        // 2 + 3 = 5
        assert_eq!(msg.height(40, &dummy_theme()), 5);
    }

    #[test]
    fn tool_call_height_zero_width() {
        let bash = BashTC::from_args("hello", false, None, None, false);
        let msg = ToolCallMessage { variant: ToolCallVariant::Bash(bash) };
        assert_eq!(msg.height(0, &dummy_theme()), 4);
    }

    // ---------------------------------------------------------------------------
    // Pending variant
    // ---------------------------------------------------------------------------

    #[test]
    fn pending_tool_call_height() {
        // Pending: header(2) + "executing..." (1) = 3
        let args = serde_json::json!({"command": "cargo build"});
        let msg = ToolCallMessage {
            variant: ToolCallVariant::Pending {
                tool_name: "bash".to_string(),
                tool_args: args,
                output: String::new(),
                animation_start: None,
                effect_added: false,
            },
        };
        assert_eq!(msg.height(80, &dummy_theme()), 3);
    }

    #[test]
    fn pending_tool_call_height_zero_width() {
        let args = serde_json::json!({"command": "cargo build"});
        let msg = ToolCallMessage {
            variant: ToolCallVariant::Pending {
                tool_name: "bash".to_string(),
                tool_args: args,
                output: String::new(),
                animation_start: None,
                effect_added: false,
            },
        };
        assert_eq!(msg.height(0, &dummy_theme()), 4);
    }

    #[test]
    fn pending_tool_call_height_with_output() {
        // Pending with output: header(2) + 3 output lines + "executing..." (1) = 6
        let args = serde_json::json!({"command": "cargo build"});
        let output = "Compiling crate1\nCompiling crate2\nCompiling crate3".to_string();
        let msg = ToolCallMessage {
            variant: ToolCallVariant::Pending {
                tool_name: "bash".to_string(),
                tool_args: args,
                output,
                animation_start: None,
                effect_added: false,
            },
        };
        assert_eq!(msg.height(80, &dummy_theme()), 6);
    }

    #[test]
    fn pending_tool_call_height_output_over_limit() {
        // 100 lines → truncated to 10 + 1 summary + "executing..." = 12 content lines
        let args = serde_json::json!({"command": "cargo build"});
        let output: String = (0..100).map(|i| format!("line {i}")).collect::<Vec<_>>().join("\n");
        let msg = ToolCallMessage {
            variant: ToolCallVariant::Pending {
                tool_name: "bash".to_string(),
                tool_args: args,
                output,
                animation_start: None,
                effect_added: false,
            },
        };
        // 2 (header+border) + 1 summary + 10 content + 1 executing = 14
        assert_eq!(msg.height(80, &dummy_theme()), 14);
    }

    #[test]
    fn extract_pending_target_bash() {
        let args = serde_json::json!({"command": "cargo test"});
        let target = ToolCallMessage::extract_pending_target("bash", &args);
        assert_eq!(target, "cargo test");
    }

    #[test]
    fn extract_pending_target_read() {
        let args = serde_json::json!({"path": "src/main.rs"});
        let target = ToolCallMessage::extract_pending_target("read", &args);
        assert_eq!(target, "src/main.rs");
    }

    #[test]
    fn extract_pending_target_write() {
        let args = serde_json::json!({"path": "output.txt", "content": "hello"});
        let target = ToolCallMessage::extract_pending_target("write", &args);
        assert_eq!(target, "output.txt");
    }

    #[test]
    fn extract_pending_target_unknown_tool() {
        let args = serde_json::json!({"foo": "bar"});
        let target = ToolCallMessage::extract_pending_target("custom_tool", &args);
        assert_eq!(target, "unknown");
    }

    #[test]
    fn extract_pending_target_missing_field() {
        let args = serde_json::json!({});
        let target = ToolCallMessage::extract_pending_target("bash", &args);
        assert_eq!(target, "unknown");
    }

    // --- Tail rendering tests (now using FilledHeaderBar) ---

    #[test]
    fn tail_rendering_shows_collapsed() {
        // 100 lines → collapsed, FilledHeaderBar::collapsed(true)
        let output: String = (0..100).map(|i| format!("line {i}")).collect::<Vec<_>>().join("\n");
        let bash = BashTC::from_args(&output, false, None, None, false);
        let msg = ToolCallMessage { variant: ToolCallVariant::Bash(bash) };
        // Collapsed: 2 (header) + 1 (collapsed indicator) = 3
        assert_eq!(msg.height(80, &dummy_theme()), 3);
    }

    #[test]
    fn expanded_shows_tail_view() {
        // 100 lines, expanded → tail view: 1 summary + 10 content + 1 meta (write has bytes)
        let output: String = (0..100).map(|i| format!("line {i}")).collect::<Vec<_>>().join("\n");
        let args = serde_json::json!({"path": "test.txt", "content": output.clone()});
        let mut write = WriteToolCall::from_args("", false, Some(&args), false);
        write.expanded = true;
        let msg = ToolCallMessage { variant: ToolCallVariant::Write(write) };
        // 2 (header) + 1 summary + 10 content + 1 meta = 14
        assert_eq!(msg.height(80, &dummy_theme()), 14);
    }

    #[test]
    fn small_output_no_toggle() {
        // 5 lines → no truncation
        let output: String = (0..5).map(|i| format!("line {i}")).collect::<Vec<_>>().join("\n");
        let bash = BashTC::from_args(&output, false, None, None, false);
        let msg = ToolCallMessage { variant: ToolCallVariant::Bash(bash) };
        // 2 (header) + 5 content = 7
        assert_eq!(msg.height(80, &dummy_theme()), 7);
    }

    #[test]
    fn pending_tail_shows_last_lines() {
        // 100 lines of output → truncated to 10 + 1 summary + "executing"
        let output: String = (0..100).map(|i| format!("line {i}")).collect::<Vec<_>>().join("\n");
        let args = serde_json::json!({"command": "cargo build"});
        let msg = ToolCallMessage {
            variant: ToolCallVariant::Pending {
                tool_name: "bash".to_string(),
                tool_args: args,
                output,
                animation_start: None,
                effect_added: false,
            },
        };
        // 2 (header) + 1 summary + 10 content + 1 executing = 14
        assert_eq!(msg.height(80, &dummy_theme()), 14);
    }

    #[test]
    fn pending_small_no_summary() {
        // 5 lines of output → no summary, just content + "executing"
        let output: String = (0..5).map(|i| format!("line {i}")).collect::<Vec<_>>().join("\n");
        let args = serde_json::json!({"command": "cargo build"});
        let msg = ToolCallMessage {
            variant: ToolCallVariant::Pending {
                tool_name: "bash".to_string(),
                tool_args: args,
                output,
                animation_start: None,
                effect_added: false,
            },
        };
        // 2 (header) + 5 content + 1 executing = 8
        assert_eq!(msg.height(80, &dummy_theme()), 8);
    }
