// Extracted tests from src/context/token_tracker.rs
// Auto-generated by extract-tests.sh

use super::TokenRateTracker;

    // ---------------------------------------------------------------------------
    // Construction
    // ---------------------------------------------------------------------------

    #[test]
    fn new_tracker_has_zero_state() {
        let tracker = TokenRateTracker::new();
        assert!(!tracker.is_streaming());
    }

    #[test]
    fn restore_sets_session_totals() {
        let tracker = TokenRateTracker::restore(1000, 50.0);
        // Session totals are restored — used by finalize_turn() for persistence.
        assert!(!tracker.is_streaming());
    }

    // ---------------------------------------------------------------------------
    // start() / pause_timing()
    // ---------------------------------------------------------------------------

    #[test]
    fn start_sets_streaming() {
        let mut tracker = TokenRateTracker::new();
        tracker.start();
        assert!(tracker.is_streaming());
    }

    #[test]
    fn start_resets_turn_counters() {
        let mut tracker = TokenRateTracker::new();
        tracker.start();
        tracker.record(35); // simulate a token
        tracker.start(); // reset
        // After reset, is_streaming is true but cumulative_chars is 0
        assert!(tracker.is_streaming());
    }

    #[test]
    fn pause_timing_breaks_measurement_chain() {
        let mut tracker = TokenRateTracker::new();
        tracker.start();
        tracker.record(35);
        tracker.pause_timing();
        // After pause, last_timestamp is None
        assert!(tracker.is_streaming()); // streaming flag is not cleared by pause
    }

    // ---------------------------------------------------------------------------
    // record()
    // ---------------------------------------------------------------------------

    #[test]
    fn record_accumulates_tokens() {
        let mut tracker = TokenRateTracker::new();
        tracker.start();
        for _ in 0..10 {
            tracker.record(35); // ~10 tokens worth of chars
        }
        // Turn tokens should have been estimated from chars
        assert!(tracker.is_streaming());
    }

    // ---------------------------------------------------------------------------
    // apply_provider_usage()
    // ---------------------------------------------------------------------------

    #[test]
    fn apply_provider_usage_overwrites_estimated_tokens() {
        let mut tracker = TokenRateTracker::new();
        tracker.start();
        // Record some chars (estimates tokens internally)
        for _ in 0..20 {
            tracker.record(35);
        }
        // Apply provider usage — should override estimate
        tracker.apply_provider_usage(50);
        // finalize should use provider-corrected tokens
        let entry = tracker.finalize_turn();
        assert_eq!(entry.unwrap().tokens, 50);
    }

    #[test]
    fn apply_provider_usage_accumulates_across_phases() {
        let mut tracker = TokenRateTracker::new();
        tracker.start();
        // Multiple record calls to accumulate inter-token time
        for _ in 0..10 {
            tracker.record(35);
        }
        tracker.apply_provider_usage(30); // first phase
        tracker.apply_provider_usage(20); // second phase
        tracker.apply_provider_usage(10); // third phase (total 60)
        let entry = tracker.finalize_turn();
        // After finalize, session totals should include the 60 tokens
        assert_eq!(entry.unwrap().tokens, 60);
    }

    // ---------------------------------------------------------------------------
    // finalize_turn()
    // ---------------------------------------------------------------------------

    #[test]
    fn finalize_turn_adds_to_session() {
        let mut tracker = TokenRateTracker::new();
        tracker.start();
        for _ in 0..10 {
            tracker.record(35);
        }
        tracker.apply_provider_usage(100);
        let entry = tracker.finalize_turn();
        assert!(entry.is_some());
        assert_eq!(entry.unwrap().tokens, 100);
        // Streaming flag should be cleared
        assert!(!tracker.is_streaming());
    }

    #[test]
    fn finalize_turn_with_zero_tokens_returns_none() {
        let mut tracker = TokenRateTracker::new();
        tracker.start();
        // No tokens recorded
        let entry = tracker.finalize_turn();
        // Returns None when tokens == 0
        assert!(entry.is_none());
    }

    #[test]
    fn finalize_turn_resets_turn_counters() {
        let mut tracker = TokenRateTracker::new();
        tracker.start();
        for _ in 0..10 {
            tracker.record(35);
        }
        tracker.apply_provider_usage(100);
        tracker.finalize_turn();
        // Streaming flag should be cleared
        assert!(!tracker.is_streaming());
    }

    #[test]
    fn finalize_turn_uses_minimum_seconds() {
        // Regression: finalize_turn must use seconds.max(0.01) for zero-duration turns
        let mut tracker = TokenRateTracker::new();
        tracker.start();
        tracker.apply_provider_usage(50);
        // No record() calls, so turn_stream_seconds == 0.0
        // finalize_turn should use 0.01 minimum
        let entry = tracker.finalize_turn();
        assert!(entry.is_some());
        let entry = entry.unwrap();
        assert!(entry.seconds >= 0.01);
    }

    #[test]
    fn finalize_turn_marks_not_streaming() {
        let mut tracker = TokenRateTracker::new();
        tracker.start();
        tracker.record(35);
        tracker.finalize_turn();
        assert!(!tracker.is_streaming());
    }

    // ---------------------------------------------------------------------------
    // Multiple turns
    // ---------------------------------------------------------------------------

    #[test]
    fn multiple_turns_accumulate_session_totals() {
        let mut tracker = TokenRateTracker::new();

        // Turn 1
        tracker.start();
        for _ in 0..10 {
            tracker.record(35);
        }
        tracker.apply_provider_usage(100);
        let entry1 = tracker.finalize_turn();
        assert_eq!(entry1.unwrap().tokens, 100);

        // Turn 2
        tracker.start();
        for _ in 0..10 {
            tracker.record(35);
        }
        tracker.apply_provider_usage(200);
        let entry2 = tracker.finalize_turn();
        assert_eq!(entry2.unwrap().tokens, 200);

        // Both turns finalized, streaming flag cleared
        assert!(!tracker.is_streaming());
    }
