// Extracted tests from src/provider/llamacpp.rs
// Auto-generated by extract-tests.sh

use super::llamacpp::to_openai_message;
use super::{Message, ToolDef};
use crate::session::ToolCall;
use async_openai::types::chat::{
    ChatCompletionRequestMessage, ChatCompletionRequestSystemMessageArgs,
    ChatCompletionRequestUserMessageArgs, ChatCompletionTool, ChatCompletionTools,
    CreateChatCompletionRequestArgs, FunctionObject,
};

    // -----------------------------------------------------------------------
    // to_openai_message — empty assistant guard
    // -----------------------------------------------------------------------

    #[test]
    fn to_openai_message_skips_empty_assistant() {
        // Assistant with no content and no tool_calls → None
        let msg = Message::Assistant {
            reasoning: String::new(),
            content: String::new(),
            tool_calls: Vec::new(),
        };
        assert!(to_openai_message(&msg).is_none(),
            "empty assistant message (no content, no tool_calls) must be skipped");
    }

    #[test]
    fn to_openai_message_keeps_assistant_with_empty_content_and_tool_calls() {
        // Assistant with empty content but tool_calls → Some
        let msg = Message::Assistant {
            reasoning: String::new(),
            content: String::new(),
            tool_calls: vec![ToolCall {
                id: "call_1".to_string(),
                name: "bash".to_string(),
                arguments: serde_json::json!({"command": "ls"}),
            }],
        };
        let result = to_openai_message(&msg);
        assert!(result.is_some(),
            "assistant with tool_calls must be kept even with empty content");
    }

    #[test]
    fn to_openai_message_assistant_content_omitted_when_empty_with_tool_calls() {
        // Match pi-coding-agent: omit content when empty and tool_calls present.
        // Sending content:"" increases empty response rate on some LLM servers.
        let msg = Message::Assistant {
            reasoning: String::new(),
            content: String::new(),
            tool_calls: vec![ToolCall {
                id: "call_1".to_string(),
                name: "bash".to_string(),
                arguments: serde_json::json!({"command": "ls"}),
            }],
        };
        let openai_msg = to_openai_message(&msg).unwrap();
        let json = serde_json::to_string(&openai_msg).unwrap();
        // Content field should be omitted (skip_serializing_if = Option::is_none)
        assert!(!json.contains(r#""content""#),
            "assistant content should be omitted when empty+tool_calls. JSON: {json}");
    }

    #[test]
    fn to_openai_message_assistant_content_kept_when_non_empty() {
        // Content should be present when non-empty (even with tool_calls)
        let msg = Message::Assistant {
            reasoning: String::new(),
            content: "Let me check.".to_string(),
            tool_calls: vec![ToolCall {
                id: "call_1".to_string(),
                name: "bash".to_string(),
                arguments: serde_json::json!({"command": "ls"}),
            }],
        };
        let openai_msg = to_openai_message(&msg).unwrap();
        let json = serde_json::to_string(&openai_msg).unwrap();
        assert!(json.contains(r#""content":"Let me check.""#),
            "assistant content should be present when non-empty. JSON: {json}");
    }

    #[test]
    fn to_openai_message_assistant_content_present_when_no_tool_calls() {
        // Verify that assistant messages without tool_calls have content field
        let msg = Message::Assistant {
            reasoning: String::new(),
            content: "hello".to_string(),
            tool_calls: vec![],
        };
        let openai_msg = to_openai_message(&msg).unwrap();
        let json = serde_json::to_string(&openai_msg).unwrap();
        assert!(json.contains(r#""content":"hello""#),
            "assistant content should be present when no tool_calls. JSON: {json}");
    }

    // -----------------------------------------------------------------------
    // print_serialized_request
    // -----------------------------------------------------------------------

    #[test]
    fn print_serialized_request() {
        let tools: Vec<ToolDef> = vec![
            ToolDef {
                name: "bash".to_string(),
                description: "Run a shell command".to_string(),
                parameters: serde_json::json!({"type":"object","properties":{"command":{"type":"string"}}}),
            },
        ];

        let msgs: Vec<ChatCompletionRequestMessage> = vec![
            ChatCompletionRequestMessage::System(
                ChatCompletionRequestSystemMessageArgs::default()
                    .content("You are a test.")
                    .build().unwrap(),
            ),
            ChatCompletionRequestMessage::User(
                ChatCompletionRequestUserMessageArgs::default()
                    .content("hello")
                    .build().unwrap(),
            ),
        ];

        let openai_req = {
            let chat_tools: Vec<ChatCompletionTools> = tools
                .iter()
                .map(|def| ChatCompletionTools::Function(ChatCompletionTool {
                    function: FunctionObject {
                        name: def.name.clone(),
                        description: Some(def.description.clone()),
                        parameters: Some(def.parameters.clone()),
                        strict: None, // omitted from JSON via skip_serializing_if
                    },
                }))
                .collect();

            let mut req = CreateChatCompletionRequestArgs::default()
                .model("qwen36")
                .messages(msgs)
                .tools(chat_tools)
                .stream(true)
                .build()
                .unwrap();

            req.stream_options = Some(
                async_openai::types::chat::ChatCompletionStreamOptions {
                    include_usage: Some(true),
                    include_obfuscation: None,
                }
            );
            req
        };

        let json = serde_json::to_string(&openai_req).unwrap();
        let val: serde_json::Value = serde_json::from_str(&json).unwrap();
        println!("\n=== Serialized request body ({} bytes) ===", json.len());
        println!("{}", serde_json::to_string_pretty(&val).unwrap());
        // Print fields that are null vs absent
        println!("\n=== Fields present ===");
        if let Some(obj) = val.as_object() {
            for (k, v) in obj {
                if v.is_null() {
                    println!("  {k} = null (PRESENT)");
                } else if v.is_boolean() && !v.as_bool().unwrap() {
                    println!("  {k} = false (PRESENT)");
                } else {
                    println!("  {k} = {v:?}");
                }
            }
        }
    }
