// Extracted tests from src/provider/mod.rs
// Auto-generated by extract-tests.sh

use super::{Message, ProviderError, ToolDef, ToolCallDelta, accumulate_tool_call, agent_message_to_message, is_context_overflow, parse_tool_call_arguments, ProviderSettings};
    use crate::session::{AgentMessage, ToolCall};
    use std::io::{Error, ErrorKind};

    // ---------------------------------------------------------------------------
    // Message::content()
    // ---------------------------------------------------------------------------

    #[test]
    fn message_content_system() {
        let msg = Message::System { content: "be helpful".to_string() };
        assert_eq!(msg.content(), "be helpful");
    }

    #[test]
    fn message_content_user() {
        let msg = Message::User { content: "hello".to_string() };
        assert_eq!(msg.content(), "hello");
    }

    #[test]
    fn message_content_assistant() {
        let msg = Message::Assistant { content: "hi there".to_string(), reasoning: String::new(), tool_calls: Vec::new() };
        assert_eq!(msg.content(), "hi there");
    }

    #[test]
    fn message_content_tool() {
        let msg = Message::Tool { tool_call_id: "call_1".to_string(), result: "42".to_string() };
        assert_eq!(msg.content(), "42");
    }

    // ---------------------------------------------------------------------------
    // agent_message_to_message
    // ---------------------------------------------------------------------------

    #[test]
    fn agent_to_message_system() {
        let agent = AgentMessage::System { content: "sys".to_string() };
        let msg = agent_message_to_message(&agent);
        assert_eq!(msg.content(), "sys");
    }

    #[test]
    fn agent_to_message_user() {
        let agent = AgentMessage::User { content: "user msg".to_string() };
        let msg = agent_message_to_message(&agent);
        assert_eq!(msg.content(), "user msg");
    }

    #[test]
    fn agent_to_message_assistant_with_tool_calls() {
        use crate::session::ContentBlock;
        let agent = AgentMessage::Assistant {
            content: vec![
                ContentBlock::Text { text: "result".to_string() },
                ContentBlock::ToolCall { tool_call: ToolCall {
                    id: "call_1".to_string(),
                    name: "my_tool".to_string(),
                    arguments: serde_json::json!({"key": "val"}),
                }},
            ],
            usage: None,
        };
        let msg = agent_message_to_message(&agent);
        match msg {
            Message::Assistant { content, reasoning, tool_calls } => {
                assert_eq!(content, "result");
                assert_eq!(reasoning, "");
                assert_eq!(tool_calls.len(), 1);
                assert_eq!(tool_calls[0].name, "my_tool");
            }
            _ => panic!("expected Assistant message"),
        }
    }

    // ---------------------------------------------------------------------------
    // accumulate_tool_call
    // ---------------------------------------------------------------------------

    #[test]
    fn accumulate_tool_call_first_delta() {
        let mut pending = Vec::new();
        let delta = ToolCallDelta {
            index: 0,
            id: Some("call_1".to_string()),
            name: Some("my_tool".to_string()),
            arguments: Some("{}".to_string()),
        };
        accumulate_tool_call(&mut pending, &delta);
        assert_eq!(pending.len(), 1);
        assert_eq!(pending[0].id, "call_1");
        assert_eq!(pending[0].name, "my_tool");
        assert_eq!(pending[0].arguments, "{}");
    }

    #[test]
    fn accumulate_tool_call_multiple_deltas() {
        let mut pending = Vec::new();

        // First delta: id + name
        accumulate_tool_call(&mut pending, &ToolCallDelta {
            index: 0,
            id: Some("call_1".to_string()),
            name: Some("my_tool".to_string()),
            arguments: None,
        });

        // Second delta: arguments fragment
        accumulate_tool_call(&mut pending, &ToolCallDelta {
            index: 0,
            id: None,
            name: None,
            arguments: Some("{\"key\":".to_string()),
        });

        // Third delta: more arguments
        accumulate_tool_call(&mut pending, &ToolCallDelta {
            index: 0,
            id: None,
            name: None,
            arguments: Some("\"val\"}".to_string()),
        });

        assert_eq!(pending[0].arguments, "{\"key\":\"val\"}");
    }

    #[test]
    fn accumulate_tool_call_gaps_in_index() {
        let mut pending = Vec::new();
        // Index 2 → should create slots 0, 1, 2
        accumulate_tool_call(&mut pending, &ToolCallDelta {
            index: 2,
            id: Some("call_3".to_string()),
            name: Some("tool_3".to_string()),
            arguments: None,
        });
        assert_eq!(pending.len(), 3);
        assert_eq!(pending[2].id, "call_3");
    }

    // ---------------------------------------------------------------------------
    // LlamaCppSettings defaults
    // ---------------------------------------------------------------------------

    #[test]
    fn llamacpp_settings_default_url() {
        let json = r#"{"type": "llamacpp"}"#;
        let ProviderSettings::LlamaCpp(s) = serde_json::from_str(json).unwrap();
        assert_eq!(s.url, "http://localhost:8080");
        assert_eq!(s.api_key, "");
    }

    #[test]
    fn llamacpp_settings_custom_values() {
        let json = r#"{"type": "llamacpp", "url": "http://example.com:9000", "api_key": "secret"}"#;
        let ProviderSettings::LlamaCpp(s) = serde_json::from_str(json).unwrap();
        assert_eq!(s.url, "http://example.com:9000");
        assert_eq!(s.api_key, "secret");
    }

    // ---------------------------------------------------------------------------
    // ToolDef
    // ---------------------------------------------------------------------------

    #[test]
    fn tooldef_serialization() {
        let tool = ToolDef {
            name: "search".to_string(),
            description: "Search the web".to_string(),
            parameters: serde_json::json!({
                "type": "object",
                "properties": {
                    "query": {"type": "string"}
                }
            }),
        };
        let json = serde_json::to_string(&tool).unwrap();
        assert!(json.contains("search"));
        assert!(json.contains("Search the web"));
    }

    // ---------------------------------------------------------------------------
    // is_context_overflow
    // ---------------------------------------------------------------------------

    #[test]
    fn is_context_overflow_detects_context_window() {
        assert!(is_context_overflow(400, "Error: context window exceeded"));
    }

    #[test]
    fn is_context_overflow_detects_max_tokens() {
        assert!(is_context_overflow(400, "max tokens exceeded for this model"));
    }

    #[test]
    fn is_context_overflow_detects_too_long() {
        assert!(is_context_overflow(400, "Input is too long"));
    }

    #[test]
    fn is_context_overflow_detects_maximum_context_length() {
        assert!(is_context_overflow(400, "Request failed: maximum context length of 32768 exceeded"));
    }

    #[test]
    fn is_context_overflow_detects_exceeds_context() {
        assert!(is_context_overflow(400, "Prompt exceeds context limit"));
    }

    #[test]
    fn is_context_overflow_detects_context_size() {
        assert!(is_context_overflow(400, "request (133988 tokens) exceeds the available context size"));
    }

    #[test]
    fn is_context_overflow_detects_exceed_context_size_error() {
        let body = r#"{"error":{"code":400,"type":"exceed_context_size_error","message":"request exceeds context size"}}"#;
        assert!(is_context_overflow(400, body));
    }

    #[test]
    fn is_context_overflow_detects_token_limit() {
        assert!(is_context_overflow(400, "Token limit reached"));
    }

    #[test]
    fn is_context_overflow_detects_413_status() {
        assert!(is_context_overflow(413, "Payload Too Large"));
    }

    #[test]
    fn is_context_overflow_case_insensitive() {
        assert!(is_context_overflow(400, "CONTEXT WINDOW EXCEEDED"));
        assert!(is_context_overflow(400, "Context Window Exceeded"));
    }

    #[test]
    fn is_context_overflow_rejects_auth_error() {
        assert!(!is_context_overflow(401, "Invalid API key"));
    }

    #[test]
    fn is_context_overflow_rejects_rate_limit() {
        assert!(!is_context_overflow(429, "Rate limit exceeded"));
    }

    #[test]
    fn is_context_overflow_rejects_server_error() {
        assert!(!is_context_overflow(500, "Internal server error"));
    }

    #[test]
    fn is_context_overflow_rejects_empty_body() {
        assert!(!is_context_overflow(400, ""));
    }

    // ---------------------------------------------------------------------------
    // ProviderError::is_retryable
    // ---------------------------------------------------------------------------

    #[test]
    fn is_retryable_network_error() {
        let err = ProviderError::Network(Error::new(ErrorKind::ConnectionRefused, "connection refused"));
        assert!(err.is_retryable());
    }

    #[test]
    fn is_retryable_serialization_error() {
        let err = ProviderError::Serialization(serde_json::from_str::<String>("invalid").unwrap_err());
        assert!(err.is_retryable());
    }

    #[test]
    fn is_retryable_empty_response() {
        let err = ProviderError::EmptyResponse { detail: "test".to_string() };
        assert!(err.is_retryable());
    }

    #[test]
    fn is_retryable_incomplete_stream() {
        let err = ProviderError::IncompleteStream { detail: "no finish_reason".to_string() };
        assert!(err.is_retryable());
    }

    #[test]
    fn is_retryable_http_429() {
        let err = ProviderError::Http { status: 429, body: "Rate limit exceeded".to_string(), retry_after: None };
        assert!(err.is_retryable());
    }

    #[test]
    fn is_retryable_http_500() {
        let err = ProviderError::Http { status: 500, body: "Internal server error".to_string(), retry_after: None };
        assert!(err.is_retryable());
    }

    #[test]
    fn is_retryable_http_502() {
        let err = ProviderError::Http { status: 502, body: "Bad gateway".to_string(), retry_after: None };
        assert!(err.is_retryable());
    }

    #[test]
    fn is_retryable_http_503() {
        let err = ProviderError::Http { status: 503, body: "Service unavailable".to_string(), retry_after: None };
        assert!(err.is_retryable());
    }

    #[test]
    fn is_retryable_http_504() {
        let err = ProviderError::Http { status: 504, body: "Gateway timeout".to_string(), retry_after: None };
        assert!(err.is_retryable());
    }

    #[test]
    fn is_retryable_http_408() {
        let err = ProviderError::Http { status: 408, body: "Request timeout".to_string(), retry_after: None };
        assert!(err.is_retryable());
    }

    #[test]
    fn is_retryable_http_409() {
        let err = ProviderError::Http { status: 409, body: "Conflict".to_string(), retry_after: None };
        assert!(err.is_retryable());
    }

    #[test]
    fn is_retryable_http_400_not_retryable() {
        let err = ProviderError::Http { status: 400, body: "Bad request".to_string(), retry_after: None };
        assert!(!err.is_retryable());
    }

    #[test]
    fn is_retryable_http_401_not_retryable() {
        let err = ProviderError::Http { status: 401, body: "Unauthorized".to_string(), retry_after: None };
        assert!(!err.is_retryable());
    }

    #[test]
    fn is_retryable_http_403_not_retryable() {
        let err = ProviderError::Http { status: 403, body: "Forbidden".to_string(), retry_after: None };
        assert!(!err.is_retryable());
    }

    #[test]
    fn is_retryable_http_404_not_retryable() {
        let err = ProviderError::Http { status: 404, body: "Not found".to_string(), retry_after: None };
        assert!(!err.is_retryable());
    }

    #[test]
    fn is_retryable_context_overflow_not_retryable() {
        let err = ProviderError::ContextOverflow { detail: "context window exceeded".to_string() };
        assert!(!err.is_retryable());
    }

    #[test]
    fn is_retryable_not_configured_not_retryable() {
        let err = ProviderError::NotConfigured("llamacpp".to_string());
        assert!(!err.is_retryable());
    }

    #[test]
    fn is_retryable_billing_quota_not_retryable() {
        let err = ProviderError::Http { status: 429, body: "insufficient_quota".to_string(), retry_after: None };
        assert!(!err.is_retryable());
    }

    #[test]
    fn is_retryable_billing_out_of_budget_not_retryable() {
        let err = ProviderError::Http { status: 400, body: "out of budget".to_string(), retry_after: None };
        assert!(!err.is_retryable());
    }

    #[test]
    fn is_retryable_billing_quota_exceeded_not_retryable() {
        let err = ProviderError::Http { status: 429, body: "quota exceeded".to_string(), retry_after: None };
        assert!(!err.is_retryable());
    }

    #[test]
    fn is_retryable_context_overflow_via_http_not_retryable() {
        let err = ProviderError::Http { status: 400, body: "context window exceeded".to_string(), retry_after: None };
        assert!(!err.is_retryable());
    }

    #[test]
    fn is_retryable_context_overflow_413_not_retryable() {
        let err = ProviderError::Http { status: 413, body: "Payload too large".to_string(), retry_after: None };
        assert!(!err.is_retryable());
    }

    // ---------------------------------------------------------------------------
    // parse_tool_call_arguments
    // ---------------------------------------------------------------------------

    #[test]
    fn parse_tool_call_arguments_valid_json() {
        let result = parse_tool_call_arguments(r#"{"path": "src/main.rs", "limit": 10}"#);
        assert!(result.is_some());
        let value = result.unwrap();
        assert_eq!(value["path"], "src/main.rs");
        assert_eq!(value["limit"], 10);
    }

    #[test]
    fn parse_tool_call_arguments_empty_string() {
        let result = parse_tool_call_arguments("");
        assert!(result.is_some());
        assert_eq!(result.unwrap(), serde_json::json!({}));
    }

    #[test]
    fn parse_tool_call_arguments_whitespace_only() {
        let result = parse_tool_call_arguments("   \n\t  ");
        assert!(result.is_some());
        assert_eq!(result.unwrap(), serde_json::json!({}));
    }

    #[test]
    fn parse_tool_call_arguments_missing_closing_brace() {
        // Incomplete JSON — missing closing `}`
        let result = parse_tool_call_arguments(r#"{"path": "src/main.rs""#);
        assert!(result.is_some(), "should repair missing closing brace");
        let value = result.unwrap();
        assert_eq!(value["path"], "src/main.rs");
    }

    #[test]
    fn parse_tool_call_arguments_trailing_comma() {
        // Trailing comma — invalid in strict JSON
        let result = parse_tool_call_arguments(r#"{"path": "src/main.rs", "limit": 10,"#);
        assert!(result.is_some(), "should handle trailing comma");
        let value = result.unwrap();
        assert_eq!(value["path"], "src/main.rs");
    }

    #[test]
    fn parse_tool_call_arguments_unclosed_string() {
        // Unclosed string value
        let result = parse_tool_call_arguments(r#"{"key": "value"#);
        assert!(result.is_some(), "should repair unclosed string");
        let value = result.unwrap();
        assert_eq!(value["key"], "value");
    }

    #[test]
    fn parse_tool_call_arguments_nested_incomplete() {
        // Nested object with missing closing braces
        let result = parse_tool_call_arguments(r#"{"outer": {"inner": "val""#);
        assert!(result.is_some(), "should repair nested incomplete JSON");
        let value = result.unwrap();
        assert_eq!(value["outer"]["inner"], "val");
    }

    #[test]
    fn parse_tool_call_arguments_empty_object() {
        let result = parse_tool_call_arguments("{}");
        assert!(result.is_some());
        assert_eq!(result.unwrap(), serde_json::json!({}));
    }

    #[test]
    fn parse_tool_call_arguments_just_opening_brace() {
        let result = parse_tool_call_arguments("{");
        assert!(result.is_some(), "should repair lone opening brace");
        assert_eq!(result.unwrap(), serde_json::json!({}));
    }

    #[test]
    fn parse_tool_call_arguments_key_without_value() {
        // Key with no value after colon
        let result = parse_tool_call_arguments(r#"{"key":"#);
        assert!(result.is_some(), "should handle key without value");
        let value = result.unwrap();
        assert!(value["key"].is_null());
    }
