// Extracted tests from src/provider/sse.rs
// Auto-generated by extract-tests.sh

use tokio::sync::mpsc;
use super::sse::{ParseState, SseChoice, SseChunk, process_sse_chunk};

    // ---------------------------------------------------------------------------
    // SseChoice — finish_reason deserialization
    // ---------------------------------------------------------------------------

    #[test]
    fn sse_choice_deserializes_with_finish_reason() {
        let json = r#"{"delta":{"content":"hello"},"finish_reason":"stop"}"#;
        let choice: SseChoice = serde_json::from_str(json).unwrap();
        assert!(choice.finish_reason.is_some());
        assert_eq!(choice.finish_reason.as_deref(), Some("stop"));
        assert!(choice.delta.is_some());
    }

    #[test]
    fn sse_choice_deserializes_without_finish_reason() {
        let json = r#"{"delta":{"content":"hello"}}"#;
        let choice: SseChoice = serde_json::from_str(json).unwrap();
        assert!(choice.finish_reason.is_none());
        assert!(choice.delta.is_some());
    }

    #[test]
    fn sse_choice_empty_defaults() {
        let json = r"{}";
        let choice: SseChoice = serde_json::from_str(json).unwrap();
        assert!(choice.finish_reason.is_none());
        assert!(choice.delta.is_none());
    }

    // ---------------------------------------------------------------------------
    // SseChunk — choices with finish_reason
    // ---------------------------------------------------------------------------

    #[test]
    fn sse_chunk_with_finish_reason_in_choice() {
        let json = r#"{"choices":[{"delta":{"content":"hi"},"finish_reason":"stop"}]}"#;
        let chunk: SseChunk = serde_json::from_str(json).unwrap();
        assert_eq!(chunk.choices.len(), 1);
        assert_eq!(chunk.choices[0].finish_reason.as_deref(), Some("stop"));
    }

    #[test]
    fn sse_chunk_empty_choices() {
        let json = r#"{"choices":[]}"#;
        let chunk: SseChunk = serde_json::from_str(json).unwrap();
        assert_eq!(chunk.choices.len(), 0);
    }

    // ---------------------------------------------------------------------------
    // process_sse_chunk — Thinking(false) on non-reasoning delta
    // ---------------------------------------------------------------------------

    #[tokio::test]
    async fn process_sse_chunk_sends_thinking_false_for_content_only() {
        let json = r#"{"choices":[{"delta":{"content":"hello"},"finish_reason":"stop"}]}"#;
        let chunk: SseChunk = serde_json::from_str(json).unwrap();

        let (tx, mut rx) = mpsc::channel(16);
        let mut state = ParseState::new();

        process_sse_chunk(chunk, &tx, &mut state).await;
        drop(tx);

        let mut chunks = Vec::new();
        while let Ok(msg) = rx.try_recv() {
            chunks.push(msg);
        }

        // Should send Thinking(false) followed by Content
        assert!(chunks.len() >= 2);
        assert!(matches!(chunks[0], super::ChatChunk::Thinking(false)));
        assert!(matches!(chunks[1], super::ChatChunk::Content(..)));
        assert!(state.finish_reason_received);
        assert_eq!(state.chunks_received, 1);
        assert!(!state.reasoning_received);
    }

    #[tokio::test]
    async fn process_sse_chunk_sends_thinking_true_for_reasoning() {
        let json = r#"{"choices":[{"delta":{"reasoning_content":"thinking...","content":"answer"}}]}"#;
        let chunk: SseChunk = serde_json::from_str(json).unwrap();

        let (tx, mut rx) = mpsc::channel(16);
        let mut state = ParseState::new();

        process_sse_chunk(chunk, &tx, &mut state).await;
        drop(tx);

        let mut chunks = Vec::new();
        while let Ok(msg) = rx.try_recv() {
            chunks.push(msg);
        }

        // Should send Thinking(true), Reasoning, Content
        assert!(chunks.len() >= 3);
        assert!(matches!(chunks[0], super::ChatChunk::Thinking(true)));
        assert!(matches!(chunks[1], super::ChatChunk::Reasoning(..)));
        assert!(state.reasoning_received);
        assert_eq!(state.chunks_received, 1);
    }
