// Extracted tests from src/tools/activate_skill.rs
// Auto-generated by extract-tests.sh

use super::activate_skill::ActivateSkillTool;
use super::ToolDefinition;

    #[test]
    fn activate_skill_definition() {
        let tool = ActivateSkillTool;
        let (name, desc, schema) = ToolDefinition::definition(&tool);
        assert_eq!(name, "activate_skill");
        assert!(desc.contains("Activate a skill"));
        assert_eq!(schema["type"], "object");
        assert_eq!(schema["required"], serde_json::json!(["name"]));
    }
