// Extracted tests from src/tools/bash.rs
// Auto-generated by extract-tests.sh

use super::bash::{sanitize_output, is_ansi_final_byte, strip_ansi, sanitize_binary, truncate_to_bytes};

    // -----------------------------------------------------------------------
    // is_ansi_final_byte
    // -----------------------------------------------------------------------

    #[test]
    fn ansi_final_byte_uppercase_letters() {
        assert!(is_ansi_final_byte('A'));
        assert!(is_ansi_final_byte('Z'));
        assert!(is_ansi_final_byte('m')); // common in color codes
    }

    #[test]
    fn ansi_final_byte_special_chars() {
        assert!(is_ansi_final_byte('~'));
        assert!(is_ansi_final_byte('='));
        assert!(is_ansi_final_byte('>'));
    }

    #[test]
    fn ansi_final_byte_rejects_digits() {
        assert!(!is_ansi_final_byte('0'));
        assert!(!is_ansi_final_byte('9'));
    }

    // -----------------------------------------------------------------------
    // sanitize_output — control characters
    // -----------------------------------------------------------------------

    #[test]
    fn sanitize_preserves_normal_text() {
        assert_eq!(sanitize_output("hello world"), "hello world");
    }

    #[test]
    fn sanitize_preserves_tab_newline_cr() {
        assert_eq!(sanitize_output("a\tb\nc\rd"), "a\tb\nc\rd");
    }

    #[test]
    fn sanitize_removes_null_bytes() {
        assert_eq!(sanitize_output("hello\x00world"), "helloworld");
    }

    #[test]
    fn sanitize_removes_backspace() {
        assert_eq!(sanitize_output("hello\x08world"), "helloworld");
    }

    #[test]
    fn sanitize_removes_bel() {
        assert_eq!(sanitize_output("hello\x07world"), "helloworld");
    }

    #[test]
    fn sanitize_removes_various_control_chars() {
        // SOH (0x01), STX (0x02), ETX (0x03), etc.
        let input = "\x01\x02\x03text\x1f";
        assert_eq!(sanitize_output(input), "text");
    }

    // -----------------------------------------------------------------------
    // sanitize_output — ANSI escape sequences
    // -----------------------------------------------------------------------

    #[test]
    fn sanitize_strips_simple_color_code() {
        // \x1b[31m = red color
        assert_eq!(sanitize_output("\x1b[31mred\x1b[0m"), "red");
    }

    #[test]
    fn sanitize_strips_color_with_semicolon_params() {
        // \x1b[38;5;196m = 256-color red
        assert_eq!(sanitize_output("\x1b[38;5;196mtext\x1b[0m"), "text");
    }

    #[test]
    fn sanitize_strips_bold_code() {
        assert_eq!(sanitize_output("\x1b[1mbold\x1b[0m"), "bold");
    }

    #[test]
    fn sanitize_strips_cursor_movement() {
        // \x1b[2A = cursor up 2 lines
        assert_eq!(sanitize_output("\x1b[2Atext"), "text");
    }

    #[test]
    fn sanitize_strips_osc_with_bel_terminator() {
        // OSC title set: \x1b]0;Title\x07
        assert_eq!(sanitize_output("\x1b]0;My Title\x07text"), "text");
    }

    #[test]
    fn sanitize_strips_osc_with_st_terminator() {
        // OSC with ST terminator: \x1b]0;Title\x1b\\
        assert_eq!(sanitize_output("\x1b]0;My Title\x1b\\text"), "text");
    }

    #[test]
    fn sanitize_strips_multiple_ansi_sequences() {
        let input = "\x1b[31mred\x1b[0m \x1b[32mgreen\x1b[0m";
        assert_eq!(sanitize_output(input), "red green");
    }

    #[test]
    fn sanitize_strips_ls_style_output() {
        // Simulated colored ls output
        let input = "\x1b[0m\x1b[01;34mfolder\x1b[0m/\n\x1b[01;32mfile.txt\x1b[0m";
        assert_eq!(sanitize_output(input), "folder/\nfile.txt");
    }

    #[test]
    fn sanitize_mixed_control_and_ansi() {
        // Mix of control chars and ANSI codes
        let input = "\x01\x1b[31mhello\x1b[0m\x07world\x00";
        assert_eq!(sanitize_output(input), "helloworld");
    }

    #[test]
    fn sanitize_empty_input() {
        assert_eq!(sanitize_output(""), "");
    }

    #[test]
    fn sanitize_only_ansi_no_text() {
        assert_eq!(sanitize_output("\x1b[31m\x1b[0m"), "");
    }

    #[test]
    fn sanitize_truncated_ansi_sequence() {
        // Incomplete ANSI sequence at end of string (no final byte)
        assert_eq!(sanitize_output("text\x1b[31"), "text");
    }

    #[test]
    fn sanitize_esc_without_introducer() {
        // ESC followed by non-introducer character
        assert_eq!(sanitize_output("a\x1bXb"), "aXb");
    }

    // -----------------------------------------------------------------------
    // sanitize_output — C1 control characters (8-bit)
    // -----------------------------------------------------------------------

    #[test]
    fn sanitize_strips_c1_csi_introducer() {
        // C1 CSI (0x9B) — 8-bit equivalent of ESC[
        // Without C1 handling, 0x9B is dropped but `[31m` leaks through
        assert_eq!(sanitize_output("\u{9B}[31mred\u{9B}[0m"), "red");
    }

    #[test]
    fn sanitize_strips_c1_osc_introducer() {
        // C1 OSC (0x9D) — 8-bit equivalent of ESC]
        assert_eq!(sanitize_output("\u{9D}0;Title\x07text"), "text");
    }

    #[test]
    fn sanitize_strips_osc_with_c1_st_terminator() {
        // OSC with C1 ST terminator (0x9C)
        assert_eq!(sanitize_output("\x1b]0;Title\u{9C}text"), "text");
    }

    #[test]
    fn sanitize_strips_c1_osc_with_c1_st() {
        // C1 OSC (0x9D) with C1 ST (0x9C)
        assert_eq!(sanitize_output("\u{9D}0;Title\u{9C}text"), "text");
    }

    #[test]
    fn sanitize_strips_c1_control_chars() {
        // C1 control characters (0x80-0x9F) should be dropped
        let input = "hello\u{80}\u{81}\u{9F}world";
        assert_eq!(sanitize_output(input), "helloworld");
    }

    #[test]
    fn sanitize_strips_del() {
        // DEL (0x7F) should be dropped
        assert_eq!(sanitize_output("hello\x7fworld"), "helloworld");
    }

    // -----------------------------------------------------------------------
    // sanitize_output — Unicode format characters
    // -----------------------------------------------------------------------

    #[test]
    fn sanitize_strips_unicode_format_chars() {
        // Unicode format characters (0xFFF9-0xFFFB) should be dropped
        let input = "hello\u{fff9}\u{fffa}\u{fffb}world";
        assert_eq!(sanitize_output(input), "helloworld");
    }

    #[test]
    fn sanitize_preserves_surrogate_space_and_bom() {
        // U+FFFF and U+FEFF are NOT format chars — should be preserved
        let input = "hello\u{ffff}\u{feff}world";
        assert_eq!(sanitize_output(input), "hello\u{ffff}\u{feff}world");
    }

    // -----------------------------------------------------------------------
    // strip_ansi — standalone tests
    // -----------------------------------------------------------------------

    #[test]
    fn strip_ansi_preserves_control_chars() {
        // strip_ansi only strips ANSI sequences; control chars pass through
        assert_eq!(strip_ansi("hello\x00world"), "hello\x00world");
    }

    #[test]
    fn strip_ansi_c1_csi_no_orphaned_fragments() {
        // Key regression test: C1 CSI should not leave orphaned `[31m`
        let result = strip_ansi("\u{9B}[31m");
        assert_eq!(result, "", "C1 CSI should be fully stripped, no orphaned fragments");
    }

    // -----------------------------------------------------------------------
    // sanitize_binary — standalone tests
    // -----------------------------------------------------------------------

    #[test]
    fn sanitize_binary_drops_all_control_ranges() {
        // C0 (0x00-0x1F), DEL (0x7F), C1 (0x80-0x9F)
        let input = "\x00\x09\x1F\x7F\u{80}\u{9F}";
        // Only \x09 (tab) should survive
        assert_eq!(sanitize_binary(input), "\x09");
    }

    // -----------------------------------------------------------------------
    // truncate_to_bytes
    // -----------------------------------------------------------------------

    #[test]
    fn truncate_to_bytes_no_truncation_needed() {
        assert_eq!(truncate_to_bytes("hello", 100), "hello");
    }

    #[test]
    fn truncate_to_bytes_exact_boundary() {
        assert_eq!(truncate_to_bytes("hello", 5), "hello");
    }

    #[test]
    fn truncate_to_bytes_ascii() {
        assert_eq!(truncate_to_bytes("hello world", 5), "hello");
    }

    #[test]
    fn truncate_to_bytes_multi_byte_safe() {
        // "é" is 2 bytes in UTF-8 (0xC3 0xA9)
        // "café" = 5 bytes: c(1) a(1) f(1) é(2)
        // Truncating at 3 bytes gives "caf" (é doesn't fit)
        assert_eq!(truncate_to_bytes("café", 3), "caf");
        // Truncating at 4 bytes also gives "caf" (byte 4 is mid-é, backs up to 3)
        assert_eq!(truncate_to_bytes("café", 4), "caf");
        // Truncating at 5 bytes gives full string
        assert_eq!(truncate_to_bytes("café", 5), "café");
    }

    #[test]
    fn truncate_to_bytes_emoji() {
        // "😀" is 4 bytes in UTF-8
        // "hi😀there" = 11 bytes: h(1) i(1) 😀(4) t(1) h(1) e(1) r(1) e(1)
        // Truncating at 2 bytes should give "hi"
        assert_eq!(truncate_to_bytes("hi😀there", 2), "hi");
        // Truncating at 3 bytes should still give "hi" (😀 is 4 bytes)
        assert_eq!(truncate_to_bytes("hi😀there", 3), "hi");
        // Truncating at 6 bytes should give "hi😀"
        assert_eq!(truncate_to_bytes("hi😀there", 6), "hi😀");
    }

    #[test]
    fn truncate_to_bytes_empty() {
        assert_eq!(truncate_to_bytes("", 10), "");
    }
