// Extracted tests from src/tools/file_queue.rs
// Auto-generated by extract-tests.sh

use super::file_queue::{with_file_queue, FILE_QUEUE, cleanup_idle_entries};
use std::sync::atomic::AtomicU32;
use std::sync::Arc;
use std::time::Duration;
use std::sync::atomic::Ordering;
use tokio::sync::Semaphore;
use std::time::Instant;

    /// Each path gets its own semaphore — concurrent ops on different files run in parallel.
    #[tokio::test]
    async fn serializes_same_file_concurrently() {
        let counter = Arc::new(AtomicU32::new(0));
        let tmp = std::env::temp_dir();
        let file_a = tmp.join("fq_test_a");
        let file_b = tmp.join("fq_test_b");

        // Ensure files exist
        let _ = tokio::fs::write(&file_a, "").await;
        let _ = tokio::fs::write(&file_b, "").await;

        let c1 = counter.clone();
        let t1 = tokio::spawn(async move {
            with_file_queue(&file_a, async {
                c1.fetch_add(1, Ordering::SeqCst);
                tokio::time::sleep(Duration::from_millis(50)).await;
                c1.fetch_add(1, Ordering::SeqCst);
            })
            .await
        });

        let c2 = counter.clone();
        let t2 = tokio::spawn(async move {
            with_file_queue(&file_b, async {
                c2.fetch_add(1, Ordering::SeqCst);
                tokio::time::sleep(Duration::from_millis(50)).await;
                c2.fetch_add(1, Ordering::SeqCst);
            })
            .await
        });

        let _ = t1.await.unwrap();
        let _ = t2.await.unwrap();

        // Both ran in parallel — counter reached 4 (each task incremented twice)
        assert_eq!(counter.load(Ordering::SeqCst), 4);
    }

    /// Operations on the same file run sequentially.
    #[tokio::test]
    async fn serializes_same_file_sequentially() {
        let tmp = std::env::temp_dir();
        let file = tmp.join("fq_test_seq");
        let _ = tokio::fs::write(&file, "").await;

        let order = Arc::new(std::sync::Mutex::new(Vec::new()));

        let f1 = file.clone();
        let o1 = order.clone();
        let t1 = tokio::spawn(async move {
            with_file_queue(&f1, async move {
                o1.lock().unwrap().push(1);
                tokio::time::sleep(Duration::from_millis(50)).await;
                o1.lock().unwrap().push(2);
            })
            .await
        });

        let f2 = file.clone();
        let o2 = order.clone();
        let t2 = tokio::spawn(async move {
            with_file_queue(&f2, async move {
                o2.lock().unwrap().push(3);
                tokio::time::sleep(Duration::from_millis(50)).await;
                o2.lock().unwrap().push(4);
            })
            .await
        });

        let _ = t1.await.unwrap();
        let _ = t2.await.unwrap();

        let order = order.lock().unwrap();
        // Operations on same file are serialized — 1,2 complete before 3,4 start
        // (or 3,4 before 1,2) — never interleaved
        assert!(
            *order == vec![1, 2, 3, 4] || *order == vec![3, 4, 1, 2],
            "Expected non-interleaved order, got: {:?}",
            *order
        );
    }

    /// Stale entries are cleaned up after exceeding the idle timeout.
    #[test]
    fn cleanup_removes_idle_entries() {
        let tmp = std::env::temp_dir();
        let file = tmp.join("fq_test_cleanup");

        // Insert entry with old timestamp
        FILE_QUEUE.semaphores.insert(
            file.clone(),
            (Arc::new(Semaphore::new(1)), Instant::now().checked_sub(Duration::from_mins(10)).unwrap()),
        );

        assert!(FILE_QUEUE.semaphores.contains_key(&file));
        cleanup_idle_entries(Instant::now());
        assert!(!FILE_QUEUE.semaphores.contains_key(&file));

        // Clean up after test
        FILE_QUEUE.semaphores.remove(&file);
    }

    /// Active entries are not removed during cleanup.
    #[test]
    fn cleanup_keeps_active_entries() {
        let tmp = std::env::temp_dir();
        let file = tmp.join("fq_test_active");

        FILE_QUEUE.semaphores.insert(
            file.clone(),
            (Arc::new(Semaphore::new(1)), Instant::now().checked_sub(Duration::from_secs(10)).unwrap()),
        );

        cleanup_idle_entries(Instant::now());
        assert!(FILE_QUEUE.semaphores.contains_key(&file));

        // Clean up after test
        FILE_QUEUE.semaphores.remove(&file);
    }
