// Extracted tests from src/tools/rtk.rs
// Auto-generated by extract-tests.sh

use super::rtk::{check_rtk_version, resolve_rtk, resolve_rtk_state, rewrite_command, RtkState};
use std::path::PathBuf;
use tempfile::TempDir;

    // ---------------------------------------------------------------------------
    // resolve_rtk
    // ---------------------------------------------------------------------------

    #[test]
    fn resolve_rtk_returns_none_when_not_installed() {
        // rtk is unlikely to be installed in CI/test env
        // If it IS installed, that's fine — test passes either way
        let _result = resolve_rtk();
        // We just verify it doesn't panic
    }

    // ---------------------------------------------------------------------------
    // resolve_rtk_state
    // ---------------------------------------------------------------------------

    #[test]
    fn resolve_rtk_state_no_binary() {
        let state = resolve_rtk_state();
        // If rtk is not installed, path is None and version_ok is false
        if state.path.is_none() {
            assert!(!state.version_ok);
            assert!(!state.is_available());
        }
    }

    #[test]
    fn resolve_rtk_state_consistent() {
        let state = resolve_rtk_state();
        // version_ok should always be false when path is None
        assert_eq!(state.path.is_none(), !state.version_ok || state.path.is_none());
    }

    // ---------------------------------------------------------------------------
    // check_rtk_version
    // ---------------------------------------------------------------------------

    #[test]
    fn check_rtk_version_nonexistent_path() {
        let result = check_rtk_version(&PathBuf::from("/nonexistent/rtk"));
        assert!(result.is_none());
    }

    #[test]
    fn check_rtk_version_shells_return_none() {
        // /bin/sh --version may not output semver, so result is None
        let result = check_rtk_version(&PathBuf::from("/bin/sh"));
        // Just verify it doesn't panic
        let _ = result;
    }

    // ---------------------------------------------------------------------------
    // rewrite_command — guards
    // ---------------------------------------------------------------------------

    #[tokio::test]
    async fn rewrite_command_empty_command_returns_none() {
        let tmp = TempDir::new().unwrap();
        let result = rewrite_command(
            &PathBuf::from("/nonexistent/rtk"),
            tmp.path(),
            "",
        )
        .await;
        assert!(result.is_none());
    }

    #[tokio::test]
    async fn rewrite_command_whitespace_only_returns_none() {
        let tmp = TempDir::new().unwrap();
        let result = rewrite_command(
            &PathBuf::from("/nonexistent/rtk"),
            tmp.path(),
            "   \t  \n  ",
        )
        .await;
        assert!(result.is_none());
    }

    #[tokio::test]
    async fn rewrite_command_already_rtk_returns_none() {
        let tmp = TempDir::new().unwrap();
        let result = rewrite_command(
            &PathBuf::from("/nonexistent/rtk"),
            tmp.path(),
            "rtk version",
        )
        .await;
        assert!(result.is_none());
    }

    #[tokio::test]
    async fn rewrite_command_rtk_with_args_returns_none() {
        let tmp = TempDir::new().unwrap();
        let result = rewrite_command(
            &PathBuf::from("/nonexistent/rtk"),
            tmp.path(),
            "rtk rewrite 'echo hello'",
        )
        .await;
        assert!(result.is_none());
    }

    #[tokio::test]
    async fn rewrite_command_leading_whitespace_rtk_returns_none() {
        let tmp = TempDir::new().unwrap();
        let result = rewrite_command(
            &PathBuf::from("/nonexistent/rtk"),
            tmp.path(),
            "  rtk version",
        )
        .await;
        assert!(result.is_none());
    }

    #[tokio::test]
    async fn rewrite_command_nonexistent_binary_returns_none() {
        let tmp = TempDir::new().unwrap();
        let result = rewrite_command(
            &PathBuf::from("/nonexistent/path/to/rtk"),
            tmp.path(),
            "echo hello",
        )
        .await;
        assert!(result.is_none());
    }

    #[tokio::test]
    async fn rewrite_command_creates_db_directory() {
        let tmp = TempDir::new().unwrap();
        let db_dir = tmp.path().join("rtk_db");
        assert!(!db_dir.exists());

        let _ = rewrite_command(
            &PathBuf::from("/nonexistent/rtk"),
            &db_dir,
            "echo hello",
        )
        .await;

        assert!(db_dir.exists());
        assert!(db_dir.is_dir());
    }

    // ---------------------------------------------------------------------------
    // RtkState
    // ---------------------------------------------------------------------------

    #[test]
    fn rtk_state_is_available_both_true() {
        let state = RtkState {
            path: Some(PathBuf::from("/usr/bin/rtk")),
            version_ok: true,
        };
        assert!(state.is_available());
    }

    #[test]
    fn rtk_state_is_available_no_path() {
        let state = RtkState {
            path: None,
            version_ok: false,
        };
        assert!(!state.is_available());
    }

    #[test]
    fn rtk_state_is_available_version_not_ok() {
        let state = RtkState {
            path: Some(PathBuf::from("/usr/bin/rtk")),
            version_ok: false,
        };
        assert!(!state.is_available());
    }
